
export const currentRanking = [
  {
    championship: "JGTC 90s 2023",
    year: "2023",
    logo: "/cupLogos/JGTClogo.png",
    colors: {
      bkg: "#000",
      head: "#bc0202",
      row: "#5b5b5b",
      txt: "white",
    },
    geral: [
      {
        pos: "1",
        driver: "José Eduardo F Filho",
        idPsn: "Dudu_fiel10",
        team: "-",
        total: 129,
      },
      {
        pos: "2",
        driver: "José Luiz de O Neto",
        idPsn: "TBR_ZELUIZ87",
        team: "TBR",
        total: 112
      },
      {
        pos: "3",
        driver: "JP Facci",
        idPsn: "JPFACCI_SPEEDBR",
        team: "SBR",
        total: 102,
      },
      {
        pos: "4",
        driver: "Luan Muniz",
        idPsn: "KMZ_Luan_Muniz89",
        team: "KMZ",
        total: 93,
      },
      {
        pos: "5",
        driver: "Marcelo Mendes",
        idPsn: "KMZ_MarceloMB",
        team: "KMZ",
        total: 92,
      },
      {
        pos: "6",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        team: "MF2",
        total: 75,
      },
      {
        pos: "7",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        team: "KMZ",
        total: 73,
      },
      {
        pos: "8",
        driver: "Rodrigo Dionizio",
        idPsn: "KmZRodrigo",
        team: "KMZ",
        total: 52,
      },
      {
        pos: "9",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        team: "SBR",
        total: 35,
      },
      {
        pos: "10",
        driver: "Rodrigo Furtile",
        idPsn: "Apex_Furtile",
        team: "Apex",
        total: 24,
      },
      {
        pos: "11",
        driver: "Ricardo Pavanelli",
        idPsn: "MF2_Pava",
        team: "MF2",
        total: 18,
      },
      {
        pos: "12",
        driver: "Cristiano Dutra",
        idPsn: "CCGTBR_Cristiano",
        team: "CCGTBR",
        total: 15,
      },
      {
        pos: "13",
        driver: "Paulo Tureck",
        idPsn: "TURECK_SPEEDBR",
        team: "SBR",
        total: 14,
      },
      {
        pos: "14",
        driver: "Carlos Godoy",
        idPsn: "MF2_TattoBrown",
        team: "MF2",
        total: 14,
      },
    ],
    principal: [
      {
        pos: "1",
        driver: "José Eduardo F Filho",
        idPsn: "Dudu_fiel10",
        team: "-",
        total: 40,
      },
      {
        pos: "2",
        driver: "JP Facci",
        idPsn: "JPFACCI_SPEEDBR",
        team: "SBR",
        total: 34,
      },
      {
        pos: "3",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        team: "MF2",
        total: 29,
      },
      {
        pos: "4",
        driver: "José Luiz de O Neto",
        idPsn: "TBR_ZELUIZ87",
        team: "TBR",
        total: 25,
      },
      {
        pos: "5",
        driver: "Marcelo Mendes",
        idPsn: "KMZ_MarceloMB",
        team: "KMZ",
        total: 22,
      },
      {
        pos: "6",
        driver: "Luan Muniz",
        idPsn: "KMZ_Luan_Muniz89",
        team: "KMZ",
        total: 19,
      },
      {
        pos: "7",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        team: "KMZ",
        total: 16,
      },
      {
        pos: "8",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        team: "SBR",
        total: 13,
      },
      {
        pos: "9",
        driver: "Rodrigo Furtile",
        idPsn: "Apex_Furtile",
        team: "Apex",
        total: 10,
      },

      {
        pos: "10",
        driver: "Rodrigo Dionizio",
        idPsn: "KmZRodrigo",
        team: "KMZ",
        total: 8,
      },
      {
        pos: "11",
        driver: "Ricardo Pavanelli",
        idPsn: "MF2_Pava",
        team: "MF2",
        total: 6,
      },
      {
        pos: "12",
        driver: "Cristiano Dutra",
        idPsn: "CCGTBR_Cristiano",
        team: "CCGTBR",
        total: 4,
      },
      {
        pos: "13",
        driver: "Paulo Tureck",
        idPsn: "TURECK_SPEEDBR",
        team: "SBR",
        total: 0,
      },
      {
        pos: "NP",
        driver: "Carlos Godoy",
        idPsn: "MF2_TattoBrown",
        team: "MF2",
        total: 0,
      },
    ],
    sprint: [
      {
        pos: "1",
        driver: "Marcelo Mendes",
        idPsn: "KMZ_MarceloMB",
        team: "KMZ",
        total: 10,
      },
      {
        pos: "2",
        driver: "Luan Muniz",
        idPsn: "KMZ_Luan_Muniz89",
        team: "KMZ",
        total: 9,
      },
      {
        pos: "3",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        team: "KMZ",
        total: 8,
      },
      {
        pos: "4",
        driver: "JP Facci",
        idPsn: "JPFACCI_SPEEDBR",
        team: "SBR",
        total: 7,
      },
      {
        pos: "5",
        driver: "José Eduardo F Filho",
        idPsn: "Dudu_fiel10",
        team: "-",
        total: 6,
      },
      {
        pos: "6",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        team: "MF2",
        total: 5,
      },
      {
        pos: "7",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        team: "SBR",
        total: 4,
      },
      {
        pos: "8",
        driver: "Paulo Tureck",
        idPsn: "TURECK_SPEEDBR",
        team: "SBR",
        total: 3,
      },
      {
        pos: "9",
        driver: "Rodrigo Dionizio",
        idPsn: "KmZRodrigo",
        team: "KMZ",
        total: 2,
      },

      {
        pos: "10",
        driver: "Rodrigo Furtile",
        idPsn: "Apex_Furtile",
        team: "Apex",
        total: 1,
      },
      {
        pos: "11",
        driver: "Cristiano Dutra",
        idPsn: "CCGTBR_Cristiano",
        team: "CCGTBR",
        total: 0,
      },
      {
        pos: "12",
        driver: "Ricardo Pavanelli",
        idPsn: "MF2_Pava",
        team: "MF2",
        total: 0,
      },
      {
        pos: "DNF",
        driver: "José Luiz de O Neto",
        idPsn: "TBR_ZELUIZ87",
        team: "TBR",
        total: 0,
      },
      {
        pos: "NP",
        driver: "Carlos Godoy",
        idPsn: "MF2_TattoBrown",
        team: "MF2",
        total: 0,
      },
    ],
  },
];