
export const championships = [
  {
    id: "jgtc23",
    title: "JGTC 90s 2023",
    logo: "/cupLogos/JGTClogo.png",
    colors: {
      bkg: "#000",
      head: "#bc0202",
      row: "#5b5b5b",
      txt: "white",
    },
    tracks: [
      {
        race: "1",
        name: "Fuji Speedway",
        url: "https://www.youtube.com/watch?v=wurs3Bi_7N0",
      },
      {
        race: "2",
        name: "Nürburgring GP",
        url: "https://www.youtube.com/watch?v=SPhsvLUOXvQ&list=PLSwFu7MJQiVewPBXY1h6Q9q5qe7LeE5JR&index=3",
      },
      { race: "3", name: "Suzuka Circuit", url: "https://www.youtube.com/watch?v=uhWltdRJ1O0&list=PLSwFu7MJQiVewPBXY1h6Q9q5qe7LeE5JR&index=4" },
      { race: "4", name: "Dragon Trail Jardins", url: "https://www.youtube.com/watch?v=ZprGS-StpLM&list=PLSwFu7MJQiVewPBXY1h6Q9q5qe7LeE5JR&index=6" },
      { race: "5", name: "Autopolis International", url: "https://www.youtube.com/watch?v=dXbGyCNAI90&list=PLSwFu7MJQiVewPBXY1h6Q9q5qe7LeE5JR&index=6" },
      { race: "6", name: "Red Bull Ring", url: "https://www.youtube.com/watch?v=pc6qS2SPvJQ&list=PLSwFu7MJQiVewPBXY1h6Q9q5qe7LeE5JR&index=7" },
      { race: "7", name: "Tokyo Exp. East", url: "/sem-video" },
      { race: "8", name: "Spa", url: "/sem-video" },
    ],
    results: [
      {
        pos: "1",
        driver: "José Eduardo F Filho",
        idPsn: "Dudu_fiel10",
        penal: "0",
        discard: "0",
        total: "248",
        points: [
          { et: "1", pt: "39" },
          { et: "2", pt: "44" },
          { et: "3", pt: "46" },
          { et: "4", pt: "44" },
          { et: "5", pt: "40" },
          { et: "6", pt: "35" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "2",
        driver: "José Luiz de O Neto",
        idPsn: "TBR_ZELUIZ87",
        penal: "0",
        discard: "0",
        total: "199",
        points: [
          { et: "1", pt: "43" },
          { et: "2", pt: "44" },
          { et: "3", pt: "25" },
          { et: "4", pt: "44" },
          { et: "5", pt: "0" },
          { et: "6", pt: "43" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "3",
        driver: "Marcelo Mendes",
        idPsn: "KMZ_MarceloMB",
        penal: "24",
        discard: "0",
        total: "194",
        points: [
          { et: "1", pt: "29" },
          { et: "2", pt: "31" },
          { et: "3", pt: "32" },
          { et: "4", pt: "34" },
          { et: "5", pt: "48" },
          { et: "6", pt: "44" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "4",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "188",
        points: [
          { et: "1", pt: "24" },
          { et: "2", pt: "37" },
          { et: "3", pt: "41" },
          { et: "4", pt: "25" },
          { et: "5", pt: "39" },
          { et: "6", pt: "22" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "5",
        driver: "Luan Muniz",
        idPsn: "KMZ_Luan_Muniz89",
        penal: "4",
        discard: "0",
        total: "177",
        points: [
          { et: "1", pt: "43" },
          { et: "2", pt: "22" },
          { et: "3", pt: "28" },
          { et: "4", pt: "21" },
          { et: "5", pt: "31" },
          { et: "6", pt: "36" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "6",
        driver: "Naldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "0",
        total: "155",
        points: [
          { et: "1", pt: "30" },
          { et: "2", pt: "19" },
          { et: "3", pt: "24" },
          { et: "4", pt: "25" },
          { et: "5", pt: "32" },
          { et: "6", pt: "25" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "7",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        penal: "12",
        discard: "0",
        total: "136",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "25" },
          { et: "3", pt: "34" },
          { et: "4", pt: "29" },
          { et: "5", pt: "23" },
          { et: "6", pt: "21" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "8",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "76",
        points: [
          { et: "1", pt: "3" },
          { et: "2", pt: "15" },
          { et: "3", pt: "17" },
          { et: "4", pt: "20" },
          { et: "5", pt: "0" },
          { et: "6", pt: "21" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "9",
        driver: "Rodrigo Furtile",
        idPsn: "Apex_Furtile",
        penal: "0",
        discard: "0",
        total: "55",
        points: [
          { et: "1", pt: "13" },
          { et: "2", pt: "0" },
          { et: "3", pt: "11" },
          { et: "4", pt: "10" },
          { et: "5", pt: "21" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "10",
        driver: "Rodrigo Dionizio",
        idPsn: "KmZRodrigo",
        penal: "0",
        discard: "0",
        total: "52",
        points: [
          { et: "1", pt: "19" },
          { et: "2", pt: "23" },
          { et: "3", pt: "10" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      }, 
      
      {
        pos: "11",
        driver: "Ricardo Pavanelli",
        idPsn: "MF2_Pava",
        penal: "0",
        discard: "0",
        total: "48",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "0" },
          { et: "3", pt: "6" },
          { et: "4", pt: "12" },
          { et: "5", pt: "8" },
          { et: "6", pt: "10" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "12",
        driver: "Cristiano Dutra",
        idPsn: "CCGTBR_Cristiano",
        penal: "0",
        discard: "0",
        total: "48",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "5" },
          { et: "3", pt: "4" },
          { et: "4", pt: "11" },
          { et: "5", pt: "12" },
          { et: "6", pt: "10" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Carlos de Godoy",
        idPsn: "MF2_TattoBrown",
        penal: "0",
        discard: "0",
        total: "45",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "8" },
          { et: "3", pt: "0" },
          { et: "4", pt: "6" },
          { et: "5", pt: "16" },
          { et: "6", pt: "9" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Paulo Tureck",
        idPsn: "TURECK_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "20",
        points: [
          { et: "1", pt: "1" },
          { et: "2", pt: "8" },
          { et: "3", pt: "5" },
          { et: "4", pt: "0" },
          { et: "5", pt: "1" },
          { et: "6", pt: "5" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "silvia22",
    title: "Nissan Silvia KUP 2022",
    logo: "/cupLogos/logoSilviaKupRed2022.png",
    colors: {
      bkg: "#181818",
      head: "#7A0404",
      row: "#e9e9e9",
      txt: "red",
    },
    tracks: [
      {
        race: "1",
        name: "Autódromo de Interlagos",
        url: "https://www.youtube.com/watch?v=H7RzZg_culQ&list=PLSwFu7MJQiVd6GIp434H91wrLedMm2GkV",
      },
      {
        race: "2",
        name: "Alsace - Vila",
        url: "https://www.youtube.com/watch?v=KjrGtETh2lY&list=PLSwFu7MJQiVd6GIp434H91wrLedMm2GkV&index=3",
      },
      {
        race: "3",
        name: "Tokyo Exp. Sul R",
        url: "https://www.youtube.com/watch?v=OPDdU9aFguQ&list=PLSwFu7MJQiVd6GIp434H91wrLedMm2GkV&index=4",
      },
      {
        race: "4",
        name: "Blue Moon Bay A",
        url: "https://www.youtube.com/watch?v=r6QzXsTzvhU&list=PLSwFu7MJQiVd6GIp434H91wrLedMm2GkV&index=5",
      },
      {
        race: "5",
        name: "Deep Forest",
        url: "https://www.youtube.com/watch?v=XCa8CoaMpqE&list=PLSwFu7MJQiVd6GIp434H91wrLedMm2GkV&index=6",
      },
      {
        race: "6",
        name: "Fuji Speedway",
        url: "https://www.youtube.com/watch?v=CM1qkWd0t3M&list=PLSwFu7MJQiVd6GIp434H91wrLedMm2GkV&index=7",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Gustavo Viaro",
        idPsn: "CCGTBR_Gustavo",
        penal: "0",
        discard: "25",
        total: "145",
        points: [
          { et: "1", pt: "30" },
          { et: "2", pt: "30" },
          { et: "3", pt: "25" },
          { et: "4", pt: "30" },
          { et: "5", pt: "30" },
          { et: "6", pt: "25" },
        ],
      },
      {
        pos: "2",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "105",
        points: [
          { et: "1", pt: "25" },
          { et: "2", pt: "25" },
          { et: "3", pt: "30" },
          { et: "4", pt: "0" },
          { et: "5", pt: "25" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "3",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "10",
        total: "96",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "15" },
          { et: "3", pt: "12" },
          { et: "4", pt: "10" },
          { et: "5", pt: "21" },
          { et: "6", pt: "30" },
        ],
      },
      {
        pos: "4",
        driver: "Naldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "3",
        total: "88",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "3" },
          { et: "3", pt: "21" },
          { et: "4", pt: "21" },
          { et: "5", pt: "18" },
          { et: "6", pt: "18" },
        ],
      },
      {
        pos: "5",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "79",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "21" },
          { et: "3", pt: "18" },
          { et: "4", pt: "18" },
          { et: "5", pt: "10" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "6",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        penal: "0",
        discard: "8",
        total: "74",
        points: [
          { et: "1", pt: "15" },
          { et: "2", pt: "18" },
          { et: "3", pt: "8" },
          { et: "4", pt: "12" },
          { et: "5", pt: "8" },
          { et: "6", pt: "21" },
        ],
      },
      {
        pos: "7",
        driver: "Kelvin Carvalho",
        idPsn: "KMZ-kelvin.c",
        penal: "0",
        discard: "5",
        total: "60",
        points: [
          { et: "1", pt: "5" },
          { et: "2", pt: "12" },
          { et: "3", pt: "6" },
          { et: "4", pt: "15" },
          { et: "5", pt: "12" },
          { et: "6", pt: "15" },
        ],
      },
      {
        pos: "8",
        driver: "Luan Muniz",
        idPsn: "KMZ_Luan_muniz89",
        penal: "0",
        discard: "0",
        total: "52",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "25" },
          { et: "5", pt: "15" },
          { et: "6", pt: "12" },
        ],
      },
      {
        pos: "9",
        driver: "Yuri Demetrius",
        idPsn: "kMz_YuriGrusH",
        penal: "0",
        discard: "6",
        total: "51",
        points: [
          { et: "1", pt: "8" },
          { et: "2", pt: "10" },
          { et: "3", pt: "15" },
          { et: "4", pt: "8" },
          { et: "5", pt: "6" },
          { et: "6", pt: "10" },
        ],
      },
      {
        pos: "10",
        driver: "Carlos de Godoy",
        idPsn: "MF2_TattoBrown",
        penal: "0",
        discard: "3",
        total: "30",
        points: [
          { et: "1", pt: "4" },
          { et: "2", pt: "3" },
          { et: "3", pt: "7" },
          { et: "4", pt: "7" },
          { et: "5", pt: "5" },
          { et: "6", pt: "7" },
        ],
      },
      {
        pos: "11",
        driver: "Cláudio Faria",
        idPsn: "CCGTBR-c_faria",
        penal: "0",
        discard: "0",
        total: "29",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "6" },
          { et: "3", pt: "4" },
          { et: "4", pt: "0" },
          { et: "5", pt: "7" },
          { et: "6", pt: "6" },
        ],
      },
      {
        pos: "12",
        driver: "Cristiano Dutra",
        idPsn: "CCGTBR_Cristiano",
        penal: "0",
        discard: "3",
        total: "27",
        points: [
          { et: "1", pt: "3" },
          { et: "2", pt: "4" },
          { et: "3", pt: "5" },
          { et: "4", pt: "6" },
          { et: "5", pt: "4" },
          { et: "6", pt: "8" },
        ],
      },
      {
        pos: "13",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "21",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "5" },
          { et: "3", pt: "10" },
          { et: "4", pt: "0" },
          { et: "5", pt: "1" },
          { et: "6", pt: "5" },
        ],
      },
      {
        pos: "14",
        driver: "Thiago Alves",
        idPsn: "ThiagoWolf",
        penal: "0",
        discard: "0",
        total: "15",
        points: [
          { et: "1", pt: "7" },
          { et: "2", pt: "8" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "15",
        driver: "Marco Antonio Soares",
        idPsn: "CRS_BillyBizzuca",
        penal: "0",
        discard: "0",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "nascar22",
    title: "Nascar Series Cup 2022",
    logo: "/cupLogos/logoNascar2022.png",
    colors: {
      bkg: "black",
      head: "#0079c2",
      row: "#5b5b5b",
      txt: "white",
    },
    tracks: [
      {
        race: "1",
        name: "Daytona Road",
        url: "https://www.youtube.com/watch?v=jQQ2WsQ-0IY&list=PLSwFu7MJQiVccKhlO0v0tuTk1RDOnI7DO",
      },
      {
        race: "2",
        name: "Blue Moon Speedway",
        url: "https://www.youtube.com/watch?v=7lX3B0TvWV4&list=PLSwFu7MJQiVccKhlO0v0tuTk1RDOnI7DO&index=2",
      },
      {
        race: "3",
        name: "Laguna Seca",
        url: "https://www.youtube.com/watch?v=NOCz04o6r3M&list=PLSwFu7MJQiVccKhlO0v0tuTk1RDOnI7DO&index=3",
      },
      {
        race: "4",
        name: "Watkins Glen",
        url: "https://www.youtube.com/watch?v=UJgcenf2Wk4&list=PLSwFu7MJQiVccKhlO0v0tuTk1RDOnI7DO&index=5",
      },
      {
        race: "5",
        name: "High Speed Ring",
        url: "https://www.youtube.com/watch?v=3tQn-Y-VlZ0&list=PLSwFu7MJQiVccKhlO0v0tuTk1RDOnI7DO&index=6",
      },
      {
        race: "6",
        name: "Daytona Tri-Oval",
        url: "https://www.youtube.com/watch?v=8lsVrvaMzF4&list=PLSwFu7MJQiVccKhlO0v0tuTk1RDOnI7DO&index=7",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Gustavo Viaro",
        idPsn: "CCGTBR_Gustavo",
        penal: "0",
        discard: "21",
        total: "157",
        points: [
          { et: "1", pt: "30" },
          { et: "2", pt: "30" },
          { et: "3", pt: "25" },
          { et: "4", pt: "30" },
          { et: "5", pt: "21" },
          { et: "6", pt: "42" },
        ],
      },
      {
        pos: "2",
        driver: "Milton Garcia",
        idPsn: "KMZ-R_SGarcia",
        penal: "0",
        discard: "0",
        total: "136",
        points: [
          { et: "1", pt: "1" },
          { et: "2", pt: "0" },
          { et: "3", pt: "30" },
          { et: "4", pt: "25" },
          { et: "5", pt: "30" },
          { et: "6", pt: "50" },
        ],
      },
      {
        pos: "3",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "12",
        total: "129",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "15" },
          { et: "3", pt: "21" },
          { et: "4", pt: "21" },
          { et: "5", pt: "12" },
          { et: "6", pt: "60" },
        ],
      },
      {
        pos: "4",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "109",
        points: [
          { et: "1", pt: "25" },
          { et: "2", pt: "12" },
          { et: "3", pt: "18" },
          { et: "4", pt: "18" },
          { et: "5", pt: "0" },
          { et: "6", pt: "36" },
        ],
      },
      {
        pos: "5",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "96",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "18" },
          { et: "3", pt: "0" },
          { et: "4", pt: "12" },
          { et: "5", pt: "18" },
          { et: "6", pt: "30" },
        ],
      },
      {
        pos: "6",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "84",
        points: [
          { et: "1", pt: "21" },
          { et: "2", pt: "21" },
          { et: "3", pt: "12" },
          { et: "4", pt: "0" },
          { et: "5", pt: "10" },
          { et: "6", pt: "20" },
        ],
      },
      {
        pos: "7",
        driver: "Yuri Demetrius",
        idPsn: "KMZ_YuriGrush",
        penal: "0",
        discard: "0",
        total: "74",
        points: [
          { et: "1", pt: "8" },
          { et: "2", pt: "10" },
          { et: "3", pt: "0" },
          { et: "4", pt: "15" },
          { et: "5", pt: "25" },
          { et: "6", pt: "16" },
        ],
      },
      {
        pos: "8",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "0",
        total: "71",
        points: [
          { et: "1", pt: "15" },
          { et: "2", pt: "7" },
          { et: "3", pt: "0" },
          { et: "4", pt: "10" },
          { et: "5", pt: "15" },
          { et: "6", pt: "24" },
        ],
      },
      {
        pos: "9",
        driver: "Cláudio Faria",
        idPsn: "CCGTBR-c_faria",
        penal: "0",
        discard: "0",
        total: "42",
        points: [
          { et: "1", pt: "5" },
          { et: "2", pt: "8" },
          { et: "3", pt: "15" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "14" },
        ],
      },
      {
        pos: "10",
        driver: "Cristiano Dutra",
        idPsn: "CCGTBR_Cristiano",
        penal: "0",
        discard: "0",
        total: "37",
        points: [
          { et: "1", pt: "4" },
          { et: "2", pt: "5" },
          { et: "3", pt: "8" },
          { et: "4", pt: "0" },
          { et: "5", pt: "8" },
          { et: "6", pt: "12" },
        ],
      },
      {
        pos: "11",
        driver: "Rafael Garcia",
        idPsn: "rafael_garcia79",
        penal: "4",
        discard: "0",
        total: "31",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "25" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "12",
        driver: "Francisco da Silva",
        idPsn: "ELEKTROEDD",
        penal: "0",
        discard: "0",
        total: "30",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "10" },
          { et: "4", pt: "3" },
          { et: "5", pt: "7" },
          { et: "6", pt: "10" },
        ],
      },
      {
        pos: "13",
        driver: "Marcos André da Silva",
        idPsn: "CCGTBR_Borges",
        penal: "0",
        discard: "0",
        total: "15",
        points: [
          { et: "1", pt: "7" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "8" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Jonathan Diego",
        idPsn: "E-Boss_Jonathan",
        penal: "0",
        discard: "0",
        total: "12",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "6" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "mazda22",
    title: "Mazda Touring Cup 2022",
    logo: "/cupLogos/logoMazda2022.png",
    colors: {
      bkg: "#312d4c",
      head: "#0d91b0",
      row: "#5b5b5b",
      txt: "#fff",
    },
    tracks: [
      {
        race: "1",
        name: "Sardegna C II",
        url: "https://www.youtube.com/watch?v=MVTw6NLUga0&list=PLSwFu7MJQiVcO5VrynUPCnXtUu3ND6741",
      },
      {
        race: "2",
        name: "Horse Thief Mile",
        url: "https://www.youtube.com/watch?v=mRBdKiqAyy0&list=PLSwFu7MJQiVcO5VrynUPCnXtUu3ND6741&index=2",
      },
      {
        race: "3",
        name: "Trial Mountain",
        url: "https://www.youtube.com/watch?v=vD0b9L4ZKlg&list=PLSwFu7MJQiVcO5VrynUPCnXtUu3ND6741&index=3",
      },
      {
        race: "4",
        name: "Tsukuba Circuit",
        url: "https://www.youtube.com/watch?v=0IgKaVzalGw&list=PLSwFu7MJQiVcO5VrynUPCnXtUu3ND6741&index=4",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Gustavo Viaro",
        idPsn: "CCGTBR_Gustavo",
        penal: "0",
        discard: "17",
        total: "60",
        points: [
          { et: "1", pt: "20" },
          { et: "2", pt: "17" },
          { et: "3", pt: "20" },
          { et: "4", pt: "20" },
        ],
      },
      {
        pos: "2",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "53",
        points: [
          { et: "1", pt: "15" },
          { et: "2", pt: "20" },
          { et: "3", pt: "18" },
          { et: "4", pt: "0" },
        ],
      },
      {
        pos: "3",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTHI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "51",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "18" },
          { et: "3", pt: "15" },
          { et: "4", pt: "0" },
        ],
      },
      {
        pos: "4",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "11",
        total: "49",
        points: [
          { et: "1", pt: "11" },
          { et: "2", pt: "15" },
          { et: "3", pt: "16" },
          { et: "4", pt: "18" },
        ],
      },
      {
        pos: "5",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "12",
        total: "48",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "16" },
          { et: "3", pt: "17" },
          { et: "4", pt: "15" },
        ],
      },
      {
        pos: "6",
        driver: "Thomas Penteado",
        idPsn: "NeoCactuar",
        penal: "0",
        discard: "0",
        total: "47",
        points: [
          { et: "1", pt: "17" },
          { et: "2", pt: "13" },
          { et: "3", pt: "0" },
          { et: "4", pt: "17" },
        ],
      },
      {
        pos: "7",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "13",
        total: "44",
        points: [
          { et: "1", pt: "13" },
          { et: "2", pt: "14" },
          { et: "3", pt: "14" },
          { et: "4", pt: "16" },
        ],
      },
      {
        pos: "8",
        driver: "José Eduardo Filho",
        idPsn: "PCR_Dudu10",
        penal: "0",
        discard: "0",
        total: "41",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "0" },
          { et: "3", pt: "11" },
          { et: "4", pt: "14" },
        ],
      },
      {
        pos: "9",
        driver: "Luis Vilches",
        idPsn: "luisvilches",
        penal: "0",
        discard: "9",
        total: "34",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "11" },
          { et: "3", pt: "9" },
          { et: "4", pt: "13" },
        ],
      },
      {
        pos: "10",
        driver: "Cléber Carlos",
        idPsn: "CLEBER_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "33",
        points: [
          { et: "1", pt: "9" },
          { et: "2", pt: "0" },
          { et: "3", pt: "12" },
          { et: "4", pt: "12" },
        ],
      },
      {
        pos: "11",
        driver: "Pedro Bernardo",
        idPsn: "Petros_pro",
        penal: "0",
        discard: "8",
        total: "29",
        points: [
          { et: "1", pt: "8" },
          { et: "2", pt: "10" },
          { et: "3", pt: "8" },
          { et: "4", pt: "11" },
        ],
      },
      {
        pos: "12",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "27",
        points: [
          { et: "1", pt: "14" },
          { et: "2", pt: "0" },
          { et: "3", pt: "13" },
          { et: "4", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Leandro Borges",
        idPsn: "Caua-1308",
        penal: "0",
        discard: "0",
        total: "22",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "12" },
          { et: "3", pt: "10" },
          { et: "4", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Luciano Five",
        idPsn: "lppfive",
        penal: "0",
        discard: "0",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "gt322",
    title: "GT3 Cup 2022",
    logo: "/cupLogos/logoGT3B2022.png",
    colors: {
      bkg: "#1d1d1d",
      head: "#00bb1c",
      row: "#000",
      txt: "white",
    },
    tracks: [
      {
        race: "1",
        name: "Laguna Seca",
        url: "https://www.youtube.com/watch?v=z6SE2sfQyoo&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=2",
      },
      {
        race: "2",
        name: "Autopolis Int.",
        url: "https://www.youtube.com/watch?v=S066ALI3W2k&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=3",
      },
      {
        race: "3",
        name: "Mount Panorama",
        url: "https://www.youtube.com/watch?v=8ZWVQLyIZm0&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=4",
      },
      {
        race: "4",
        name: "Autodromo Monza S/C",
        url: "https://www.youtube.com/watch?v=EPSd8WNxaKM&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=5",
      },
      {
        race: "5",
        name: "Blue Moon Speedway",
        url: "https://www.youtube.com/watch?v=HS-NiNCkJjs&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=6",
      },
      {
        race: "6",
        name: "Autódromo de Intelagos",
        url: "https://www.youtube.com/watch?v=SJPn0wqooe4&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=7",
      },
      {
        race: "7",
        name: "Nürburgring 24h",
        url: "https://www.youtube.com/watch?v=mDMXyBQK1aw&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=8",
      },
      {
        race: "8",
        name: "Spa",
        url: "https://www.youtube.com/watch?v=-wF-Ls1kmIE&list=PLSwFu7MJQiVfW1VzdZQFPjV5O9s_VTDsi&index=9",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Gustavo Viaro",
        idPsn: "CCGTBR_Gustavo",
        penal: "0",
        discard: "25",
        total: "170",
        points: [
          { et: "1", pt: "25" },
          { et: "2", pt: "25" },
          { et: "3", pt: "30" },
          { et: "4", pt: "30" },
          { et: "5", pt: "25" },
          { et: "6", pt: "25" },
          { et: "7", pt: "30" },
          { et: "8", pt: "30" },
        ],
      },
      {
        pos: "2",
        driver: "José Eduardo Filho",
        idPsn: "PCR_Dudu10",
        penal: "0",
        discard: "3",
        total: "142",
        points: [
          { et: "1", pt: "30" },
          { et: "2", pt: "12" },
          { et: "3", pt: "6" },
          { et: "4", pt: "21" },
          { et: "5", pt: "3" },
          { et: "6", pt: "30" },
          { et: "7", pt: "18" },
          { et: "8", pt: "25" },
        ],
      },
      {
        pos: "3",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "120",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "15" },
          { et: "3", pt: "0" },
          { et: "4", pt: "9" },
          { et: "5", pt: "30" },
          { et: "6", pt: "21" },
          { et: "7", pt: "15" },
          { et: "8", pt: "18" },
        ],
      },
      {
        pos: "4",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        penal: "0",
        discard: "0",
        total: "116",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "1" },
          { et: "3", pt: "15" },
          { et: "4", pt: "15" },
          { et: "5", pt: "21" },
          { et: "6", pt: "0" },
          { et: "7", pt: "25" },
          { et: "8", pt: "21" },
        ],
      },
      {
        pos: "5",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "6",
        total: "105",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "9" },
          { et: "3", pt: "12" },
          { et: "4", pt: "18" },
          { et: "5", pt: "15" },
          { et: "6", pt: "18" },
          { et: "7", pt: "21" },
          { et: "8", pt: "12" },
        ],
      },
      {
        pos: "6",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "100",
        points: [
          { et: "1", pt: "3" },
          { et: "2", pt: "18" },
          { et: "3", pt: "18" },
          { et: "4", pt: "25" },
          { et: "5", pt: "9" },
          { et: "6", pt: "15" },
          { et: "7", pt: "12" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "7",
        driver: "Equipe BVR",
        idPsn: "-",
        penal: "8",
        discard: "1",
        total: "98",
        points: [
          { et: "1", pt: "1" },
          { et: "2", pt: "30" },
          { et: "3", pt: "21" },
          { et: "4", pt: "12" },
          { et: "5", pt: "18" },
          { et: "6", pt: "1" },
          { et: "7", pt: "9" },
          { et: "8", pt: "15" },
        ],
      },
      {
        pos: "8",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "65",
        points: [
          { et: "1", pt: "15" },
          { et: "2", pt: "6" },
          { et: "3", pt: "25" },
          { et: "4", pt: "6" },
          { et: "5", pt: "0" },
          { et: "6", pt: "12" },
          { et: "7", pt: "0" },
          { et: "8", pt: "1" },
        ],
      },
      {
        pos: "9",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "1",
        total: "54",
        points: [
          { et: "1", pt: "9" },
          { et: "2", pt: "21" },
          { et: "3", pt: "1" },
          { et: "4", pt: "3" },
          { et: "5", pt: "6" },
          { et: "6", pt: "3" },
          { et: "7", pt: "6" },
          { et: "8", pt: "6" },
        ],
      },
      {
        pos: "10",
        driver: "Cléber Carlos",
        idPsn: "CLEBER_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "25",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "3" },
          { et: "4", pt: "1" },
          { et: "5", pt: "0" },
          { et: "6", pt: "9" },
          { et: "7", pt: "3" },
          { et: "8", pt: "9" },
        ],
      },
      {
        pos: "11",
        driver: "Alessandro Gratão",
        idPsn: "AleGratao75",
        penal: "0",
        discard: "0",
        total: "24",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "3" },
          { et: "3", pt: "9" },
          { et: "4", pt: "0" },
          { et: "5", pt: "12" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "12",
        driver: "Eduardo Schaarschmidt",
        idPsn: "DuduToretto",
        penal: "0",
        discard: "0",
        total: "21",
        points: [
          { et: "1", pt: "21" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Marco Godoi",
        idPsn: "Cel_God",
        penal: "0",
        discard: "0",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Luis Vilches",
        idPsn: "luisvilches",
        penal: "0",
        discard: "0",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "gr421",
    title: "Multi Gr.4 $tream 2021",
    logo: "/cupLogos/logoGr4B2021.png",
    colors: {
      bkg: "black",
      head: "#d19a00",
      row: "#5b5b5b",
      txt: "white",
    },
    tracks: [
      {
        race: "1",
        name: "Red Bull Ring",
        url: "https://www.youtube.com/watch?v=GJeOuBGOK4A&list=PLSwFu7MJQiVd5XPl5JbMi3bspD0BV1CLd",
      },
      {
        race: "2",
        name: "Big Willow",
        url: "https://www.youtube.com/watch?v=FMZcYtckYB4&list=PLSwFu7MJQiVd5XPl5JbMi3bspD0BV1CLd&index=2",
      },
      {
        race: "3",
        name: "Catalunha",
        url: "https://www.youtube.com/watch?v=CrNOwRbUX8E&list=PLSwFu7MJQiVd5XPl5JbMi3bspD0BV1CLd&index=3",
      },
      {
        race: "4",
        name: "Blue Moon Speedway A",
        url: "https://www.youtube.com/watch?v=UMjT8j-kxSo&list=PLSwFu7MJQiVd5XPl5JbMi3bspD0BV1CLd&index=4",
      },
      {
        race: "5",
        name: "Autodromo Monza",
        url: "https://www.youtube.com/watch?v=GXrO7oVLaus&list=PLSwFu7MJQiVd5XPl5JbMi3bspD0BV1CLd&index=5",
      },
      {
        race: "6",
        name: "Autódromo de Interlagos",
        url: "https://www.youtube.com/watch?v=c_LKo6QjDNk&list=PLSwFu7MJQiVd5XPl5JbMi3bspD0BV1CLd&index=6",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Gustavo Viaro",
        idPsn: "CCGTBR_Gustavo",
        penal: "0",
        discard: "-",
        total: "131",
        points: [
          { et: "1", pt: "30" },
          { et: "2", pt: "21" },
          { et: "3", pt: "25" },
          { et: "4", pt: "0" },
          { et: "5", pt: "30" },
          { et: "6", pt: "25" },
        ],
      },
      {
        pos: "2",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "127",
        points: [
          { et: "1", pt: "25" },
          { et: "2", pt: "15" },
          { et: "3", pt: "18" },
          { et: "4", pt: "30" },
          { et: "5", pt: "18" },
          { et: "6", pt: "21" },
        ],
      },
      {
        pos: "3",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "121",
        points: [
          { et: "1", pt: "21" },
          { et: "2", pt: "18" },
          { et: "3", pt: "21" },
          { et: "4", pt: "21" },
          { et: "5", pt: "25" },
          { et: "6", pt: "15" },
        ],
      },
      {
        pos: "4",
        driver: "João Cláudio Pessoa",
        idPsn: "GRID_JOAOSOF",
        penal: "0",
        discard: "-",
        total: "115",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "30" },
          { et: "3", pt: "30" },
          { et: "4", pt: "25" },
          { et: "5", pt: "0" },
          { et: "6", pt: "30" },
        ],
      },
      {
        pos: "5",
        driver: "Rafael Garcia",
        idPsn: "rafael_garcia79",
        penal: "0",
        discard: "-",
        total: "97",
        points: [
          { et: "1", pt: "15" },
          { et: "2", pt: "25" },
          { et: "3", pt: "15" },
          { et: "4", pt: "18" },
          { et: "5", pt: "15" },
          { et: "6", pt: "9" },
        ],
      },
      {
        pos: "6",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "-",
        total: "63",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "0" },
          { et: "3", pt: "9" },
          { et: "4", pt: "15" },
          { et: "5", pt: "21" },
          { et: "6", pt: "12" },
        ],
      },
      {
        pos: "7",
        driver: "Gustavo dos Santos",
        idPsn: "Ghustaw",
        penal: "0",
        discard: "-",
        total: "36",
        points: [
          { et: "1", pt: "9" },
          { et: "2", pt: "0" },
          { et: "3", pt: "12" },
          { et: "4", pt: "12" },
          { et: "5", pt: "0" },
          { et: "6", pt: "3" },
        ],
      },
      {
        pos: "8",
        driver: "Luis Vilches",
        idPsn: "luisvilches",
        penal: "0",
        discard: "-",
        total: "31",
        points: [
          { et: "1", pt: "1" },
          { et: "2", pt: "6" },
          { et: "3", pt: "3" },
          { et: "4", pt: "9" },
          { et: "5", pt: "12" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "9",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "27",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "3" },
          { et: "5", pt: "0" },
          { et: "6", pt: "6" },
        ],
      },
      {
        pos: "10",
        driver: "Murilo H da Silva",
        idPsn: "MYTH_MuriloSilva",
        penal: "4",
        discard: "-",
        total: "26",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "12" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "18" },
        ],
      },
      {
        pos: "11",
        driver: "Marco Godoi",
        idPsn: "Cel_God",
        penal: "0",
        discard: "-",
        total: "19",
        points: [
          { et: "1", pt: "3" },
          { et: "2", pt: "3" },
          { et: "3", pt: "6" },
          { et: "4", pt: "6" },
          { et: "5", pt: "0" },
          { et: "6", pt: "1" },
        ],
      },
      {
        pos: "12",
        driver: "Ronan Costa Berto",
        idPsn: "Bertorcsb",
        penal: "0",
        discard: "-",
        total: "1",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "1" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Marco Santos",
        idPsn: "MarcodiSantti",
        penal: "0",
        discard: "-",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Leandro Borges",
        idPsn: "Caua-1308",
        penal: "0",
        discard: "-",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "toyota21",
    title: "Toyota $tream Light 2021",
    logo: "/cupLogos/logoToyotaLightB2021.png",
    colors: {
      bkg: "black",
      head: "#d19a00",
      row: "#5b5b5b",
      txt: "white",
    },
    tracks: [
      {
        race: "1",
        name: "BB Raceway",
        url: "https://www.youtube.com/watch?v=1lBrTgnbsKk&list=PLSwFu7MJQiVf_5Upgbi8OQV9HhaA3MBPh",
      },
      {
        race: "2",
        name: "Tsukuba Circuit",
        url: "https://www.youtube.com/watch?v=ADVoINU_ApE&list=PLSwFu7MJQiVf_5Upgbi8OQV9HhaA3MBPh&index=2",
      },
      {
        race: "3",
        name: "Autopolis Curta",
        url: "https://www.youtube.com/watch?v=Q658KXQpFNc&list=PLSwFu7MJQiVf_5Upgbi8OQV9HhaA3MBPh&index=3",
      },
      {
        race: "4",
        name: "Kyoto - Yamagiwa",
        url: "https://www.youtube.com/watch?v=gJbGbGSlnaM&list=PLSwFu7MJQiVf_5Upgbi8OQV9HhaA3MBPh&index=4",
      },
      {
        race: "5",
        name: "Suzuka Circuit",
        url: "https://www.youtube.com/watch?v=rd4nAdD7KCw&list=PLSwFu7MJQiVf_5Upgbi8OQV9HhaA3MBPh&index=5",
      },
      {
        race: "6",
        name: "Fuji - Curto",
        url: "https://www.youtube.com/watch?v=IgXnXtc0xb0&list=PLSwFu7MJQiVf_5Upgbi8OQV9HhaA3MBPh&index=6",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "104",
        points: [
          { et: "1", pt: "20" },
          { et: "2", pt: "16" },
          { et: "3", pt: "20" },
          { et: "4", pt: "16" },
          { et: "5", pt: "18" },
          { et: "6", pt: "14" },
        ],
      },
      {
        pos: "2",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        penal: "0",
        discard: "-",
        total: "98",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "20" },
          { et: "3", pt: "14" },
          { et: "4", pt: "18" },
          { et: "5", pt: "10" },
          { et: "6", pt: "18" },
        ],
      },
      {
        pos: "3",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "84",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "18" },
          { et: "3", pt: "16" },
          { et: "4", pt: "14" },
          { et: "5", pt: "20" },
          { et: "6", pt: "16" },
        ],
      },
      {
        pos: "4",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "-",
        total: "80",
        points: [
          { et: "1", pt: "14" },
          { et: "2", pt: "0" },
          { et: "3", pt: "18" },
          { et: "4", pt: "20" },
          { et: "5", pt: "16" },
          { et: "6", pt: "12" },
        ],
      },
      {
        pos: "5",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "80",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "12" },
          { et: "3", pt: "8" },
          { et: "4", pt: "10" },
          { et: "5", pt: "14" },
          { et: "6", pt: "20" },
        ],
      },
      {
        pos: "6",
        driver: "Thiago Lima",
        idPsn: "ThiagoGt_Rbr_Am",
        penal: "0",
        discard: "-",
        total: "48",
        points: [
          { et: "1", pt: "8" },
          { et: "2", pt: "14" },
          { et: "3", pt: "12" },
          { et: "4", pt: "6" },
          { et: "5", pt: "8" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "7",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "-",
        total: "44",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "10" },
          { et: "4", pt: "12" },
          { et: "5", pt: "12" },
          { et: "6", pt: "10" },
        ],
      },
      {
        pos: "8",
        driver: "Paulo Ramos",
        idPsn: "Paulo_baiano27",
        penal: "6",
        discard: "-",
        total: "32",
        points: [
          { et: "1", pt: "4" },
          { et: "2", pt: "10" },
          { et: "3", pt: "6" },
          { et: "4", pt: "8" },
          { et: "5", pt: "2" },
          { et: "6", pt: "8" },
        ],
      },
      {
        pos: "9",
        driver: "Marco Aurélio Cerqueira",
        idPsn: "Marco_RJ",
        penal: "3",
        discard: "-",
        total: "25",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "6" },
          { et: "3", pt: "4" },
          { et: "4", pt: "4" },
          { et: "5", pt: "4" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "10",
        driver: "Cléber Carlos",
        idPsn: "CLEBER_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "24",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "4" },
          { et: "3", pt: "0" },
          { et: "4", pt: "2" },
          { et: "5", pt: "0" },
          { et: "6", pt: "6" },
        ],
      },
      {
        pos: "11",
        driver: "Walter de Moraes",
        idPsn: "waltinhorpm74",
        penal: "0",
        discard: "-",
        total: "12",
        points: [
          { et: "1", pt: "2" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "6" },
          { et: "6", pt: "4" },
        ],
      },
      {
        pos: "12",
        driver: "Lucas Macam",
        idPsn: "KMZ_Lucas",
        penal: "0",
        discard: "-",
        total: "8",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "8" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Aldair Martins",
        idPsn: "Aldair_Martins",
        penal: "0",
        discard: "-",
        total: "6",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Walter dos Santos",
        idPsn: "walter-wa42",
        penal: "0",
        discard: "-",
        total: "4",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "2" },
          { et: "3", pt: "2" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "bmw21",
    title: "BMW $tream Challenge 2021",
    logo: "/cupLogos/logoBMWB2021.png",
    colors: {
      bkg: "black",
      head: "#d19a00",
      row: "#5b5b5b",
      txt: "white",
    },
    tracks: [
      {
        race: "1",
        name: "Brands Hatch",
        url: "https://www.youtube.com/watch?v=uXiE-cQv8uA&list=PLSwFu7MJQiVfRkk-O-vXSHHQz_p2-0AKb",
      },
      {
        race: "2",
        name: "Lago Maggiore O II",
        url: "https://www.youtube.com/watch?v=g8wuI4FaEbA&list=PLSwFu7MJQiVfRkk-O-vXSHHQz_p2-0AKb&index=2",
      },
      {
        race: "3",
        name: "Goodwood",
        url: "https://www.youtube.com/watch?v=M7MxxBSX0ZM&list=PLSwFu7MJQiVfRkk-O-vXSHHQz_p2-0AKb&index=3",
      },
      {
        race: "4",
        name: "Red Bull Ring Curta",
        url: "https://www.youtube.com/watch?v=klqeIMElXxo&list=PLSwFu7MJQiVfRkk-O-vXSHHQz_p2-0AKb&index=4",
      },
      {
        race: "5",
        name: "Sardegna C II",
        url: "https://www.youtube.com/watch?v=Vs9IdDZ5iQY&list=PLSwFu7MJQiVfRkk-O-vXSHHQz_p2-0AKb&index=5",
      },
      {
        race: "6",
        name: "Nürburgring GP",
        url: "https://www.youtube.com/watch?v=64b7T7jSZXw&list=PLSwFu7MJQiVfRkk-O-vXSHHQz_p2-0AKb&index=6",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Ronan Costa Berto",
        idPsn: "Bertorcsb",
        penal: "0",
        discard: "-",
        total: "98",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "20" },
          { et: "3", pt: "20" },
          { et: "4", pt: "14" },
          { et: "5", pt: "20" },
          { et: "6", pt: "12" },
        ],
      },
      {
        pos: "2",
        driver: "Luan Muniz",
        idPsn: "Luan_mmuniz89",
        penal: "0",
        discard: "-",
        total: "78",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "10" },
          { et: "3", pt: "16" },
          { et: "4", pt: "18" },
          { et: "5", pt: "10" },
          { et: "6", pt: "14" },
        ],
      },
      {
        pos: "3",
        driver: "Luis VIlches",
        idPsn: "luisvilches",
        penal: "0",
        discard: "-",
        total: "78",
        points: [
          { et: "1", pt: "14" },
          { et: "2", pt: "14" },
          { et: "3", pt: "18" },
          { et: "4", pt: "10" },
          { et: "5", pt: "14" },
          { et: "6", pt: "8" },
        ],
      },
      {
        pos: "4",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "-",
        total: "74",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "20" },
          { et: "5", pt: "18" },
          { et: "6", pt: "20" },
        ],
      },
      {
        pos: "5",
        driver: "Gustavo dos Santos",
        idPsn: "Ghustaw",
        penal: "0",
        discard: "-",
        total: "60",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "16" },
          { et: "3", pt: "12" },
          { et: "4", pt: "6" },
          { et: "5", pt: "8" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "6",
        driver: "Alessandro Gratão",
        idPsn: "AlêGratão76",
        penal: "7",
        discard: "-",
        total: "59",
        points: [
          { et: "1", pt: "4" },
          { et: "2", pt: "18" },
          { et: "3", pt: "0" },
          { et: "4", pt: "12" },
          { et: "5", pt: "16" },
          { et: "6", pt: "16" },
        ],
      },
      {
        pos: "7",
        driver: "Eduardo Alecrim",
        idPsn: "Alecrim7",
        penal: "12",
        discard: "-",
        total: "54",
        points: [
          { et: "1", pt: "20" },
          { et: "2", pt: "12" },
          { et: "3", pt: "0" },
          { et: "4", pt: "16" },
          { et: "5", pt: "0" },
          { et: "6", pt: "18" },
        ],
      },
      {
        pos: "8",
        driver: "Marco Aurélio Cerqueira",
        idPsn: "Marco_RJ",
        penal: "0",
        discard: "-",
        total: "40",
        points: [
          { et: "1", pt: "8" },
          { et: "2", pt: "8" },
          { et: "3", pt: "8" },
          { et: "4", pt: "4" },
          { et: "5", pt: "12" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "9",
        driver: "Algberg Veloso",
        idPsn: "Berg_pvh",
        penal: "0",
        discard: "-",
        total: "38",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "6" },
          { et: "3", pt: "14" },
          { et: "4", pt: "8" },
          { et: "5", pt: "0" },
          { et: "6", pt: "10" },
        ],
      },
      {
        pos: "10",
        driver: "Cléber Carlos",
        idPsn: "CLEBER_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "22",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "2" },
          { et: "3", pt: "6" },
          { et: "4", pt: "2" },
          { et: "5", pt: "6" },
          { et: "6", pt: "6" },
        ],
      },
      {
        pos: "11",
        driver: "Yuri Stolai",
        idPsn: "Punhalkiller",
        penal: "3",
        discard: "-",
        total: "17",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "0" },
          { et: "3", pt: "10" },
          { et: "4", pt: "0" },
          { et: "5", pt: "4" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "12",
        driver: "Luciano Braga",
        idPsn: "KymMastter-kmz",
        penal: "0",
        discard: "-",
        total: "2",
        points: [
          { et: "1", pt: "2" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "0",
        points: [
          { et: "0", pt: "6" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Leandro Borges",
        idPsn: "Caua-1308",
        penal: "5",
        discard: "-",
        total: "-1",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "4" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "redware21",
    title: "Redware GT500 Advanced 2021",
    logo: "/cupLogos/logoRedware2021.png",
    colors: {
      bkg: "#000",
      head: "#BE0000",
      row: "#5b5b5b",
      txt: "#fff",
    },
    tracks: [
      {
        race: "1",
        name: "Autodromo Monza",
        url: "https://www.youtube.com/watch?v=4YF1EOC4dKg&list=PLSwFu7MJQiVerMlMr03uw9aHgSIatE52s",
      },
      {
        race: "2",
        name: "La Sarthe",
        url: "https://www.youtube.com/watch?v=WTEJAnbbdjI&list=PLSwFu7MJQiVerMlMr03uw9aHgSIatE52s&index=2",
      },
      {
        race: "3",
        name: "Mount Panorama",
        url: "https://www.youtube.com/watch?v=QQecFFetPGM&list=PLSwFu7MJQiVerMlMr03uw9aHgSIatE52s&index=3",
      },
      {
        race: "4",
        name: "Kyoto Miyabi + Yamagiwa",
        url: "https://www.youtube.com/watch?v=1w6gp7yfRL4&list=PLSwFu7MJQiVerMlMr03uw9aHgSIatE52s&index=5",
      },
      { race: "5", name: "Saint Croix A", url: "/sem-video" },
      {
        race: "6",
        name: "Spa",
        url: "https://www.youtube.com/watch?v=MQ5x-6rj0xQ&list=PLSwFu7MJQiVerMlMr03uw9aHgSIatE52s&index=5",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Murilo H da Silva",
        idPsn: "MYTH_MuriloSilva",
        penal: "0",
        discard: "0",
        total: "194",
        points: [
          { et: "1", pt: "40" },
          { et: "2", pt: "40" },
          { et: "3", pt: "40" },
          { et: "4", pt: "34" },
          { et: "5", pt: "0" },
          { et: "6", pt: "40" },
        ],
      },
      {
        pos: "2",
        driver: "Gustavo Viaro",
        idPsn: "CCGTBR_Gustavo",
        penal: "0",
        discard: "0",
        total: "139",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "34" },
          { et: "3", pt: "0" },
          { et: "4", pt: "40" },
          { et: "5", pt: "40" },
          { et: "6", pt: "25" },
        ],
      },
      {
        pos: "3",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "16",
        total: "134",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "25" },
          { et: "3", pt: "22" },
          { et: "4", pt: "28" },
          { et: "5", pt: "28" },
          { et: "6", pt: "31" },
        ],
      },
      {
        pos: "4",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "131",
        points: [
          { et: "1", pt: "22" },
          { et: "2", pt: "22" },
          { et: "3", pt: "25" },
          { et: "4", pt: "0" },
          { et: "5", pt: "34" },
          { et: "6", pt: "28" },
        ],
      },
      {
        pos: "5",
        driver: "Leonardo Guain",
        idPsn: "leoguain",
        penal: "0",
        discard: "0",
        total: "131",
        points: [
          { et: "1", pt: "28" },
          { et: "2", pt: "19" },
          { et: "3", pt: "28" },
          { et: "4", pt: "25" },
          { et: "5", pt: "31" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "6",
        driver: "José Eduardo Filho",
        idPsn: "PCR_Dudu10",
        penal: "0",
        discard: "0",
        total: "128",
        points: [
          { et: "1", pt: "34" },
          { et: "2", pt: "16" },
          { et: "3", pt: "31" },
          { et: "4", pt: "0" },
          { et: "5", pt: "25" },
          { et: "6", pt: "22" },
        ],
      },
      {
        pos: "7",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "10",
        discard: "0",
        total: "117",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "28" },
          { et: "3", pt: "34" },
          { et: "4", pt: "31" },
          { et: "5", pt: "0" },
          { et: "6", pt: "34" },
        ],
      },
      {
        pos: "8",
        driver: "Eduardo Schaarschmidt",
        idPsn: "DuduToretto",
        penal: "5",
        discard: "0",
        total: "57",
        points: [
          { et: "1", pt: "31" },
          { et: "2", pt: "31" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "9",
        driver: "Thomas Penteado",
        idPsn: "NeoCactuar",
        penal: "0",
        discard: "0",
        total: "41",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "22" },
          { et: "5", pt: "0" },
          { et: "6", pt: "19" },
        ],
      },
      {
        pos: "10",
        driver: "Fábian Viegas",
        idPsn: "FABIAN_SPEEDBR",
        penal: "0",
        discard: "0",
        total: "38",
        points: [
          { et: "1", pt: "25" },
          { et: "2", pt: "13" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "11",
        driver: "Paulo Tureck",
        idPsn: "TURECK_SPEEDBR",
        penal: "15",
        discard: "0",
        total: "37",
        points: [
          { et: "1", pt: "19" },
          { et: "2", pt: "6" },
          { et: "3", pt: "0" },
          { et: "4", pt: "19" },
          { et: "5", pt: "0" },
          { et: "6", pt: "8" },
        ],
      },
      {
        pos: "12",
        driver: "Eduardo Alecrim",
        idPsn: "Alecrim7",
        penal: "0",
        discard: "0",
        total: "14",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "4" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Francisco da Silva",
        idPsn: "ELEKTROEDD",
        penal: "0",
        discard: "0",
        total: "10",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "10" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Jeferson de Souza",
        idPsn: "Jefimwn221",
        penal: "0",
        discard: "0",
        total: "8",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "8" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },
  {
    id: "mazda21",
    title: "Mazda Touring Cup 2021",
    logo: "/cupLogos/logoMazda2021.png",
    colors: {
      bkg: "#312d4c",
      head: "#0d91b0",
      row: "#5b5b5b",
      txt: "#fff",
    },
    tracks: [
      {
        race: "1",
        name: "Kyoto Miyabi",
        url: "https://www.youtube.com/watch?v=bkArz6uiqcg&list=PLSwFu7MJQiVddRStWAJU6ZTpnpdxrlykd",
      },
      {
        race: "2",
        name: "Suzuka Leste",
        url: "https://www.youtube.com/watch?v=c3-ijCzD7sY&list=PLSwFu7MJQiVddRStWAJU6ZTpnpdxrlykd&index=2",
      },
      {
        race: "3",
        name: "Laggo Maggiore C",
        url: "https://www.youtube.com/watch?v=gcxp3KY8g2I&list=PLSwFu7MJQiVddRStWAJU6ZTpnpdxrlykd&index=3",
      },
      {
        race: "4",
        name: "Sardegna C",
        url: "https://www.youtube.com/watch?v=T8E0ad2Sals&list=PLSwFu7MJQiVddRStWAJU6ZTpnpdxrlykd&index=4",
      },
      {
        race: "5",
        name: "Autopolis Curta",
        url: "https://www.youtube.com/watch?v=AQ8ab1OFJTI&list=PLSwFu7MJQiVddRStWAJU6ZTpnpdxrlykd&index=5",
      },
      {
        race: "6",
        name: "Laguna Seca",
        url: "https://www.youtube.com/watch?v=726MofK242E&list=PLSwFu7MJQiVddRStWAJU6ZTpnpdxrlykd&index=6",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "104",
        points: [
          { et: "1", pt: "20" },
          { et: "2", pt: "16" },
          { et: "3", pt: "20" },
          { et: "4", pt: "16" },
          { et: "5", pt: "18" },
          { et: "6", pt: "14" },
        ],
      },
      {
        pos: "2",
        driver: "Gerson Garcia",
        idPsn: "Gersão Hamilton",
        penal: "0",
        discard: "-",
        total: "98",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "20" },
          { et: "3", pt: "14" },
          { et: "4", pt: "18" },
          { et: "5", pt: "10" },
          { et: "6", pt: "18" },
        ],
      },
      {
        pos: "3",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "84",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "18" },
          { et: "3", pt: "16" },
          { et: "4", pt: "14" },
          { et: "5", pt: "20" },
          { et: "6", pt: "16" },
        ],
      },
      {
        pos: "4",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "-",
        total: "80",
        points: [
          { et: "1", pt: "14" },
          { et: "2", pt: "0" },
          { et: "3", pt: "18" },
          { et: "4", pt: "20" },
          { et: "5", pt: "16" },
          { et: "6", pt: "12" },
        ],
      },
      {
        pos: "5",
        driver: "Fabiano Furini",
        idPsn: "FURINI_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "80",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "12" },
          { et: "3", pt: "8" },
          { et: "4", pt: "10" },
          { et: "5", pt: "14" },
          { et: "6", pt: "20" },
        ],
      },
      {
        pos: "6",
        driver: "Thiago Lima",
        idPsn: "ThiagoGt_Rbr_Am",
        penal: "0",
        discard: "-",
        total: "48",
        points: [
          { et: "1", pt: "8" },
          { et: "2", pt: "14" },
          { et: "3", pt: "12" },
          { et: "4", pt: "6" },
          { et: "5", pt: "8" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "7",
        driver: "Ednaldo Martins",
        idPsn: "KMZ_Naldo",
        penal: "0",
        discard: "-",
        total: "44",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "10" },
          { et: "4", pt: "12" },
          { et: "5", pt: "12" },
          { et: "6", pt: "10" },
        ],
      },
      {
        pos: "8",
        driver: "Paulo Ramos",
        idPsn: "Paulo_baiano27",
        penal: "6",
        discard: "-",
        total: "32",
        points: [
          { et: "1", pt: "4" },
          { et: "2", pt: "10" },
          { et: "3", pt: "6" },
          { et: "4", pt: "8" },
          { et: "5", pt: "2" },
          { et: "6", pt: "8" },
        ],
      },
      {
        pos: "9",
        driver: "Marco Aurélio Cerqueira",
        idPsn: "Marco_RJ",
        penal: "3",
        discard: "-",
        total: "25",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "6" },
          { et: "3", pt: "4" },
          { et: "4", pt: "4" },
          { et: "5", pt: "4" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "10",
        driver: "Cléber Carlos",
        idPsn: "CLEBER_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "24",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "4" },
          { et: "3", pt: "0" },
          { et: "4", pt: "2" },
          { et: "5", pt: "0" },
          { et: "6", pt: "6" },
        ],
      },
      {
        pos: "11",
        driver: "Walter de Moraes",
        idPsn: "waltinhorpm74",
        penal: "0",
        discard: "-",
        total: "12",
        points: [
          { et: "1", pt: "2" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "6" },
          { et: "6", pt: "4" },
        ],
      },
      {
        pos: "12",
        driver: "Lucas Macam",
        idPsn: "KMZ_Lucas",
        penal: "0",
        discard: "-",
        total: "8",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "8" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Aldair Martins",
        idPsn: "Aldair_Martins",
        penal: "0",
        discard: "-",
        total: "6",
        points: [
          { et: "1", pt: "6" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Walter dos Santos",
        idPsn: "walter-wa42",
        penal: "0",
        discard: "-",
        total: "4",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "2" },
          { et: "3", pt: "2" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
        ],
      },
    ],
  },

  {
    id: "porsche21",
    title: "Porsche Cup Gemignani 2021",
    logo: "/cupLogos/logoPorscheCup2021.png",
    colors: {
      bkg: "#000",
      head: "#d97316",
      row: "#1d1d1d",
      txt: "#fff",
    },
    tracks: [
      {
        race: "1",
        name: "Autopolis Int.",
        url: "https://www.youtube.com/watch?v=MXD32Id_M-U&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz",
      },
      {
        race: "2",
        name: "Sardegna A II",
        url: "https://www.youtube.com/watch?v=VSSQwoKKles&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=2",
      },
      {
        race: "3",
        name: "Autodromo Monza",
        url: "https://www.youtube.com/watch?v=GzXkHndakm8&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=3",
      },
      {
        race: "4",
        name: "Mount Panorama",
        url: "https://www.youtube.com/watch?v=aSBq4k_3EEs&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=4",
      },
      {
        race: "5",
        name: "Lago Maggiore L",
        url: "https://www.youtube.com/watch?v=RopFqVA2KJQ&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=5",
      },
      {
        race: "6",
        name: "Fuji Speedway",
        url: "https://www.youtube.com/watch?v=9cn5ekIqdf4&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=6",
      },
      {
        race: "7",
        name: "Spa",
        url: "https://www.youtube.com/watch?v=BSHEBWdPXko&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=7",
      },
      {
        race: "8",
        name: "Red Bull Ring",
        url: "https://www.youtube.com/watch?v=jSKhIBa9_gk&list=PLSwFu7MJQiVdzJARtlGp0Zt4MckTSOvEz&index=8",
      },
    ],
    results: [
      {
        pos: "1",
        driver: "Luis Ferruthio",
        idPsn: "FERRUTH_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "143",
        points: [
          { et: "1", pt: "17" },
          { et: "2", pt: "18" },
          { et: "3", pt: "18" },
          { et: "4", pt: "17" },
          { et: "5", pt: "18" },
          { et: "6", pt: "20" },
          { et: "7", pt: "20" },
          { et: "8", pt: "15" },
        ],
      },
      {
        pos: "2",
        driver: "Ronald Carvalho",
        idPsn: "roonald_f1",
        penal: "0",
        discard: "-",
        total: "134",
        points: [
          { et: "1", pt: "18" },
          { et: "2", pt: "0" },
          { et: "3", pt: "20" },
          { et: "4", pt: "20" },
          { et: "5", pt: "20" },
          { et: "6", pt: "18" },
          { et: "7", pt: "18" },
          { et: "8", pt: "20" },
        ],
      },
      {
        pos: "3",
        driver: "José Eduardo Filho",
        idPsn: "PCR_Dudu10",
        penal: "0",
        discard: "-",
        total: "133",
        points: [
          { et: "1", pt: "20" },
          { et: "2", pt: "17" },
          { et: "3", pt: "17" },
          { et: "4", pt: "16" },
          { et: "5", pt: "16" },
          { et: "6", pt: "14" },
          { et: "7", pt: "17" },
          { et: "8", pt: "16" },
        ],
      },
      {
        pos: "4",
        driver: "Leonardo Guain",
        idPsn: "leoguain",
        penal: "0",
        discard: "-",
        total: "120",
        points: [
          { et: "1", pt: "16" },
          { et: "2", pt: "15" },
          { et: "3", pt: "16" },
          { et: "4", pt: "18" },
          { et: "5", pt: "14" },
          { et: "6", pt: "13" },
          { et: "7", pt: "14" },
          { et: "8", pt: "14" },
        ],
      },
      {
        pos: "5",
        driver: "Marco Santos",
        idPsn: "MarcodiSantti",
        penal: "0",
        discard: "-",
        total: "110",
        points: [
          { et: "1", pt: "15" },
          { et: "2", pt: "11" },
          { et: "3", pt: "15" },
          { et: "4", pt: "15" },
          { et: "5", pt: "15" },
          { et: "6", pt: "15" },
          { et: "7", pt: "13" },
          { et: "8", pt: "11" },
        ],
      },
      {
        pos: "6",
        driver: "João Paulo Facci",
        idPsn: "JPFACCI_SPEEDBR",
        penal: "0",
        discard: "-",
        total: "108",
        points: [
          { et: "1", pt: "14" },
          { et: "2", pt: "20" },
          { et: "3", pt: "11" },
          { et: "4", pt: "0" },
          { et: "5", pt: "17" },
          { et: "6", pt: "17" },
          { et: "7", pt: "12" },
          { et: "8", pt: "17" },
        ],
      },
      {
        pos: "7",
        driver: "Jeferson Luis de Souza",
        idPsn: "Jefimwn221",
        penal: "5",
        discard: "-",
        total: "100",
        points: [
          { et: "1", pt: "12" },
          { et: "2", pt: "14" },
          { et: "3", pt: "12" },
          { et: "4", pt: "14" },
          { et: "5", pt: "13" },
          { et: "6", pt: "12" },
          { et: "7", pt: "15" },
          { et: "8", pt: "13" },
        ],
      },
      {
        pos: "8",
        driver: "Rafael Garcia",
        idPsn: "rafael_garcia79",
        penal: "5",
        discard: "-",
        total: "96",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "16" },
          { et: "3", pt: "14" },
          { et: "4", pt: "10" },
          { et: "5", pt: "11" },
          { et: "6", pt: "16" },
          { et: "7", pt: "16" },
          { et: "8", pt: "18" },
        ],
      },
      {
        pos: "9",
        driver: "Luis Henrique Vilches",
        idPsn: "luisvilches",
        penal: "3",
        discard: "-",
        total: "87",
        points: [
          { et: "1", pt: "11" },
          { et: "2", pt: "13" },
          { et: "3", pt: "10" },
          { et: "4", pt: "12" },
          { et: "5", pt: "12" },
          { et: "6", pt: "11" },
          { et: "7", pt: "11" },
          { et: "8", pt: "10" },
        ],
      },
      {
        pos: "10",
        driver: "Marco Aurélio Cerqueira",
        idPsn: "Marco_RJ",
        penal: "0",
        discard: "-",
        total: "80",
        points: [
          { et: "1", pt: "13" },
          { et: "2", pt: "12" },
          { et: "3", pt: "13" },
          { et: "4", pt: "0" },
          { et: "5", pt: "10" },
          { et: "6", pt: "10" },
          { et: "7", pt: "10" },
          { et: "8", pt: "12" },
        ],
      },
      {
        pos: "11",
        driver: "Paulo Henrique Monte",
        idPsn: "PRBR_PH",
        penal: "0",
        discard: "-",
        total: "67",
        points: [
          { et: "1", pt: "10" },
          { et: "2", pt: "10" },
          { et: "3", pt: "8" },
          { et: "4", pt: "13" },
          { et: "5", pt: "8" },
          { et: "6", pt: "9" },
          { et: "7", pt: "0" },
          { et: "8", pt: "9" },
        ],
      },
      {
        pos: "12",
        driver: "Taynam Magalhães",
        idPsn: "TayMaga",
        penal: "0",
        discard: "-",
        total: "29",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "9" },
          { et: "4", pt: "11" },
          { et: "5", pt: "9" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "13",
        driver: "Eduardo Alecrim Morais",
        idPsn: "Alecrim7",
        penal: "0",
        discard: "-",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
      {
        pos: "14",
        driver: "Matheus Souza",
        idPsn: "AIR_FORCE_ONE",
        penal: "0",
        discard: "-",
        total: "0",
        points: [
          { et: "1", pt: "0" },
          { et: "2", pt: "0" },
          { et: "3", pt: "0" },
          { et: "4", pt: "0" },
          { et: "5", pt: "0" },
          { et: "6", pt: "0" },
          { et: "7", pt: "0" },
          { et: "8", pt: "0" },
        ],
      },
    ],
  },
];

