
export const records = [
  {
    idRecord: 1,
    track: "Alsace",
    records: [
      {
        championship: "Nissan Silvia Kup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Nissan Silvia Gr.4",
        date: "20/10/2022",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:59.771",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:59.940",
      },
    ],
  },
  {
    idRecord: 2,
    track: "Autódromo de Interlagos",
    records: [
      {
        championship: "Multi Gr.4 $tream",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.4",
        date: "",
        idDriverPole: "45",
        driverPole: "João Cláudio Pessoa",
        timePole: "1:36.720",
        idDriverVMR: "45",
        driverVMR: "João Cláudio Pessoa",
        timeVMR: "1:36.873",
      },
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:31.459",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:32.180",
      },
      {
        championship: "Nissan Silvia Kup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Nissan Silvia Gr.4",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:37.649",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:37.776",
      },
    ],
  },
  {
    idRecord: 3,
    track: "Autodromo Monza",
    records: [
      {
        championship: "Multi Gr.4 $tream",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.4",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:56.476",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:56.416",
      },
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:38.436",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:38.282",
      },
    ],
  },
  {
    idRecord: 4,
    track: "Autodromo Monza S/C",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:38.627",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:38.500",
      },
      {
        championship: "Redware GT500",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.2",
        date: "",
        idDriverPole: "19",
        driverPole: "Murilo Silva",
        timePole: "1:29.735",
        idDriverVMR: "19",
        driverVMR: "Murilo Silva",
        timeVMR: "1:30.278",
      },
    ],
  },
  {
    idRecord: 5,
    track: "Autopolis Curta",
    records: [
      {
        championship: "Mazda Touring Cup",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "5",
        driverPole: "João Paulo Facci",
        timePole: "1:23.248",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:23.155",
      },
      {
        championship: "Toyota $tream Light",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Toyota SF-R",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:16.760",
        idDriverVMR: "39",
        driverVMR: "Thiago dos S Lima",
        timeVMR: "1:16.927",
      },
    ],
  },
  {
    idRecord: 6,
    track: "Autopolis International",
    records: [
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:45.881",
        idDriverVMR: "2",
        driverVMR: "Rafael Garcia",
        timeVMR: "1:45.836",
      },
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "2",
        driverPole: "Rafael Garcia",
        timePole: "1:45.101",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "1:45.351",
      },
    ],
  },
  {
    idRecord: 7,
    track: "BB Raceway",
    records: [
      {
        championship: "Toyota $tream Light",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Toyota SF-R",
        date: "",
        idDriverPole: "29",
        driverPole: "Bruno Borges",
        timePole: "0:32.027",
        idDriverVMR: "36",
        driverVMR: "Fabiano Furini",
        timeVMR: "0:32.321",
      },
    ],
  },
  {
    idRecord: 8,
    track: "Willow Springs: Big Willow",
    records: [
      {
        championship: "Multi Gr.4 $tream",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.4",
        date: "",
        idDriverPole: "45",
        driverPole: "João Cláudio Pessoa",
        timePole: "1:15.794",
        idDriverVMR: "45",
        driverVMR: "João Cláudio Pessoa",
        timeVMR: "1:15.979",
      },
    ],
  },
  {
    idRecord: 9,
    track: "Blue Moon Bay A",
    records: [
      {
        championship: "Nissan Silvia Kup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Nissan Silvia Gr.4",
        date: "",
        idDriverPole: "36",
        driverPole: "Fabiano Furini",
        timePole: "1:12.364",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:12.357",
      },
    ],
  },
  {
    idRecord: 10,
    track: "Blue Moon Speedway",
    records: [
      {
        championship: "Multi Gr.4 $tream",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.4",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:11.778",
        idDriverVMR: "45",
        driverVMR: "João Cláudio Pessoa",
        timeVMR: "1:10.716",
      },
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "38",
        driverPole: "Gerson Garcia",
        timePole: "0:43.312",
        idDriverVMR: "44",
        driverVMR: "Ednaldo Martins",
        timeVMR: "0:43.830",
      },
      {
        championship: "Nascar Series Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Camaro ZL1",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "0:43.399",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "0:43.640",
      },
    ],
  },
  {
    idRecord: 11,
    track: "Brands Hatch",
    records: [
      {
        championship: "BMW $tream Challenge",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "BMW M3 Evolution 89",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:45.787",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:45.595",
      },
    ],
  },
  {
    idRecord: 12,
    track: "Barcelona-Catalunha",
    records: [
      {
        championship: "Multi Gr.4 $tream",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.4",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:51.631",
        idDriverVMR: "45",
        driverVMR: "João Cláudio Pessoa",
        timeVMR: "1:50.507",
      },
    ],
  },
  {
    idRecord: 13,
    track: "Daytona Road Course",
    records: [
      {
        championship: "Nascar Series Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Camaro ZL1",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:42.684",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:43.209",
      },
    ],
  },
  {
    idRecord: 14,
    track: "Daytona Tri-Oval",
    records: [
      {
        championship: "Nascar Series Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Camaro ZL1",
        date: "",
        idDriverPole: "44",
        driverPole: "Ednaldo Martins",
        timePole: "0:41.485",
        idDriverVMR: "47",
        driverVMR: "Milton Garcia",
        timeVMR: "0:41.739",
      },
    ],
  },
  {
    idRecord: 15,
    track: "Deep Forest Raceway",
    records: [
      {
        championship: "Nissan Silvia Kup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Nissan Silvia Gr.4",
        date: "",
        idDriverPole: "44",
        driverPole: "Ednaldo Martins",
        timePole: "1:33.642",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:33.572",
      },
    ],
  },
  {
    idRecord: 16,
    track: "Fuji Curta",
    records: [
      {
        championship: "Toyota $tream Light",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Toyota SF-R",
        date: "",
        idDriverPole: "38",
        driverPole: "Gerson Garcia",
        timePole: "1:48.381",
        idDriverVMR: "6",
        driverVMR: "Luis Ferruthio",
        timeVMR: "1:48.679",
      },
    ],
  },
  {
    idRecord: 17,
    track: "Fuji Speedway",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:37.789",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:37.811",
      },
      {
        championship: "JGTC 90s",
        year: "2023",
        platform: "Gran Turismo 7",
        category: "GT500 90s",
        date: "02/02/2023",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "1:37.907",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "1:37.751",
      },
    ],
  },
  {
    idRecord: 18,
    track: "Goodwood Motorsport",
    records: [
      {
        championship: "BMW $tream Challenge",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "BMW M3 Evolution 89",
        date: "",
        idDriverPole: "25",
        driverPole: "Ronan C S Berto",
        timePole: "1:28.499",
        idDriverVMR: "25",
        driverVMR: "Ronan C S Berto",
        timeVMR: "1:28.608",
      },
    ],
  },
  {
    idRecord: 19,
    track: "High Speed Ring",
    records: [
      {
        championship: "Nascar Series Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Camaro ZL1",
        date: "",
        idDriverPole: "36",
        driverPole: "Fabiano Furini",
        timePole: "1:05.247",
        idDriverVMR: "47",
        driverVMR: "Milton Garcia",
        timeVMR: "1:05.306",
      },
    ],
  },
  {
    idRecord: 20,
    track: "Horse Thief Mile",
    records: [
      {
        championship: "Mazda Touring Mini Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "6",
        driverPole: "Luis Ferruthio",
        timePole: "0:56.032",
        idDriverVMR: "5",
        driverVMR: "João Paulo Facci",
        timeVMR: "0:56.717",
      },
    ],
  },

  {
    idRecord: 21,
    track: "Kyoto Miyabi",
    records: [
      {
        championship: "Mazda Touring Cup",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "2",
        driverPole: "Rafael Garcia",
        timePole: "0:45.746",
        idDriverVMR: "2",
        driverVMR: "Rafael Garcia",
        timeVMR: "0:45.935",
      },
    ],
  },
  {
    idRecord: 22,
    track: "Kyoto Yamagiwa",
    records: [
      {
        championship: "Toyota $tream Light",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Toyota SF-R",
        date: "",
        idDriverPole: "6",
        driverPole: "Luis Ferruthio",
        timePole: "1:47.853",
        idDriverVMR: "6",
        driverVMR: "Luis Ferruthio",
        timeVMR: "1:47.933",
      },
    ],
  },
  {
    idRecord: 23,
    track: "Kyoto Yamagiwa + Miyabi",
    records: [
      {
        championship: "Redware GT500",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.2",
        date: "",
        idDriverPole: "19",
        driverPole: "Murilo Silva",
        timePole: "2:04.764",
        idDriverVMR: "19",
        driverVMR: "Murilo Silva",
        timeVMR: "2:04.152",
      },
    ],
  },
  {
    idRecord: 24,
    track: "La Sarthe",
    records: [
      {
        championship: "Redware GT500",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.2",
        date: "",
        idDriverPole: "19",
        driverPole: "Murilo Silva",
        timePole: "3:35.903",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "3:35.739",
      },
    ],
  },
  {
    idRecord: 25,
    track: "Lago Maggiore C",
    records: [
      {
        championship: "Mazda Touring Cup",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "0:55.051",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "0:55.249",
      },
    ],
  },
  {
    idRecord: 26,
    track: "Lago Maggiore L",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:17.264",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:17.664",
      },
    ],
  },
  {
    idRecord: 27,
    track: "Lago Maggiore O II",
    records: [
      {
        championship: "BMW $tream Challenge",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "BMW M3 Evolution 89",
        date: "",
        idDriverPole: "13",
        driverPole: "Eduardo Alecrim",
        timePole: "1:44.696",
        idDriverVMR: "25",
        driverVMR: "Ronan C S Berto",
        timeVMR: "1:45.052",
      },
    ],
  },
  {
    idRecord: 28,
    track: "Laguna Seca",
    records: [
      {
        championship: "Mazda Touring Cup",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "5",
        driverPole: "João Paulo Facci",
        timePole: "1:40.952",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:41.164",
      },
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "1:22.290",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "1:22.291",
      },
      {
        championship: "Nascar Series Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Camaro ZL1",
        date: "",
        idDriverPole: "47",
        driverPole: "Milton Garcia",
        timePole: "1:21.931",
        idDriverVMR: "47",
        driverVMR: "Milton Garcia",
        timeVMR: "1:23.216",
      },
    ],
  },
  {
    idRecord: 29,
    track: "Mount Panorama",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "2:02.189",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "2:02.463",
      },
      {
        championship: "Redware GT500",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.2",
        date: "",
        idDriverPole: "19",
        driverPole: "Murilo Silva",
        timePole: "1:51.219",
        idDriverVMR: "19",
        driverVMR: "Murilo Silva",
        timeVMR: "1:52.084",
      },
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "-",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "2:03.085",
      },
    ],
  },
  {
    idRecord: 30,
    track: "Nürburgring 24H",
    records: [
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "8:15.670",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "8:16.617",
      },
    ],
  },
  {
    idRecord: 31,
    track: "Nürburgring GP",
    records: [
      {
        championship: "BMW $tream Challenge",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "BMW M3 Evolution 89",
        date: "",
        idDriverPole: "13",
        driverPole: "Eduardo Alecrim",
        timePole: "2:28.236",
        idDriverVMR: "13",
        driverVMR: "Eduardo Alecrim",
        timeVMR: "2:27.996",
      },
      {
        championship: "JGTC 90s",
        year: "2023",
        platform: "Gran Turismo 7",
        category: "GT500 90s",
        date: "09/02/2023",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "1:55.084",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "1:54.713",
      },
    ],
  },
  {
    idRecord: 32,
    track: "Red Bull Ring",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:39.766",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:39.655",
      },
      {
        championship: "Multi Gr.4 $tream",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.4",
        date: "",
        idDriverPole: "2",
        driverPole: "Rafael Garcia",
        timePole: "1:35.799",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:35.796",
      },
    ],
  },
  {
    idRecord: 33,
    track: "Red Bull Ring Curta",
    records: [
      {
        championship: "BMW $tream Challenge",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "BMW M3 Evolution 89",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:01.670",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:01.961",
      },
    ],
  },
  {
    idRecord: 34,
    track: "Saint Croix A",
    records: [
      {
        championship: "Redware GT500",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.2",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "-",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "-",
      },
    ],
  },
  {
    idRecord: 35,
    track: "Sardegna A II",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "-",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "-",
      },
    ],
  },
  {
    idRecord: 36,
    track: "Sardegna C",
    records: [
      {
        championship: "Mazda Touring Mini Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:01.272",
        idDriverVMR: "4",
        driverVMR: "Ronald Carvalho",
        timeVMR: "1:01.928",
      },
    ],
  },
  {
    idRecord: 37,
    track: "Sardegna C II",
    records: [
      {
        championship: "BMW $tream Challenge",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "BMW M3 Evolution 89",
        date: "",
        idDriverPole: "25",
        driverPole: "Ronan C S Berto",
        timePole: "1:07.204",
        idDriverVMR: "25",
        driverVMR: "Ronan C S Berto",
        timeVMR: "1:07.348",
      },
      {
        championship: "Mazda Touring Cup",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "4",
        driverPole: "Ronald Carvalho",
        timePole: "1:06.493",
        idDriverVMR: "15",
        driverVMR: "Fábian Viegas",
        timeVMR: "1:06.806",
      },
    ],
  },
  {
    idRecord: 38,
    track: "Spa-francorchamps",
    records: [
      {
        championship: "Porsche Cup Gemignani",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Porsche RSR Gr.3",
        date: "",
        idDriverPole: "6",
        driverPole: "Luis Ferruthio",
        timePole: "2:18.287",
        idDriverVMR: "7",
        driverVMR: "Marco Santos",
        timeVMR: "2:17.932",
      },
      {
        championship: "Redware GT500",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Gr.2",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "2:24.195",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "2:24.744",
      },
      {
        championship: "GT3 Cup",
        year: "2022",
        platform: "Gran Turismo Sport",
        category: "Gr.3",
        date: "",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "2:18.331",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "2:19.370",
      },
    ],
  },
  {
    idRecord: 39,
    track: "Suzuka Circuit",
    records: [
      {
        championship: "Toyota $tream Light",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Toyota SF-R",
        date: "",
        idDriverPole: "5",
        driverPole: "João Paulo Facci",
        timePole: "2:18.057",
        idDriverVMR: "44",
        driverVMR: "Ednaldo Martins",
        timeVMR: "2:19.403",
      },
      {
        championship: "Nissan Silvia Kup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Nissan Silvia Gr.4",
        date: "",
        idDriverPole: "36",
        driverPole: "Fabiano Furini",
        timePole: "2:09.471",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "2:09.781",
      },
      {
        championship: "JGTC 90s",
        year: "2023",
        platform: "Gran Turismo 7",
        category: "GT500 90s",
        date: "16/02/2023",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "1:59.216",
        idDriverVMR: "3",
        driverVMR: "José Eduardo Filho",
        timeVMR: "1:58.993",
      },
    ],
  },
  {
    idRecord: 40,
    track: "Suzuka Leste",
    records: [
      {
        championship: "Mazda Touring Cup",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "3",
        driverPole: "José Eduardo Filho",
        timePole: "0:58.501",
        idDriverVMR: "6",
        driverVMR: "Luis Ferruthio",
        timeVMR: "0:58.663",
      },
    ],
  },
  {
    idRecord: 41,
    track: "Tokyo Exp. Sul R",
    records: [
      {
        championship: "Nissan Silvia Kup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Nissan Silvia Gr.4",
        date: "",
        idDriverPole: "6",
        driverPole: "Luis Ferruthio",
        timePole: "2:06.584",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "2:06.205",
      },
    ],
  },
  {
    idRecord: 42,
    track: "Trial Mountain",
    records: [
      {
        championship: "Mazda Touring Mini Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "5",
        driverPole: "João Paulo Facci",
        timePole: "2:10.574",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "2:12.229",
      },
    ],
  },
  {
    idRecord: 43,
    track: "Tsukuba Circuit",
    records: [
      {
        championship: "Toyota $tream Light",
        year: "2021",
        platform: "Gran Turismo Sport",
        category: "Toyota SF-R",
        date: "",
        idDriverPole: "38",
        driverPole: "Gerson Garcia",
        timePole: "1:01.229",
        idDriverVMR: "36",
        driverVMR: "Fabiano Furini",
        timeVMR: "1:01.276",
      },
      {
        championship: "Mazda Touring Mini Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Mazda Roadster",
        date: "",
        idDriverPole: "21",
        driverPole: "Gustavo Viaro",
        timePole: "1:01.556",
        idDriverVMR: "6",
        driverVMR: "Luis Ferruthio",
        timeVMR: "1:02.356",
      },
    ],
  },
  {
    idRecord: 44,
    track: "Watkins Glen Curta",
    records: [
      {
        championship: "Nascar Series Cup",
        year: "2022",
        platform: "Gran Turismo 7",
        category: "Camaro ZL1",
        date: "",
        idDriverPole: "47",
        driverPole: "Milton Garcia",
        timePole: "1:06.882",
        idDriverVMR: "21",
        driverVMR: "Gustavo Viaro",
        timeVMR: "1:06.887",
      },
    ],
  },
];