import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { Page } from "components/Page";
import { Content } from "components/Content";
import { PageTitle } from "@/components/PageTitle";

import { DriversList } from "@/components/DriversList";

function Pilotos({
  pageTitle,
  description,
  title,
  drivers,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { asPath } = useRouter();

  return (
    <React.Fragment>
      <Head>
        <title>{pageTitle}</title>
        <meta name={pageTitle} content={description} />
      </Head>

      <Page title={pageTitle} description={description}>
        <Content>
          <PageTitle pageTitle={title} pageUrl={asPath} />
          <DriversList drivers={drivers} />
        </Content>
      </Page>
    </React.Fragment>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pageTitle = "Pilotos - Brasil Virtual Racing";
  const title = "Estatísticas de Pilotos";
  const description = "Lista de pilotos e suas estatísticas na Liga BVR.";
  const drivers = [
    {
      idDriver: 21,
      driver: "Gustavo Viaro",
      idPsn: "CCGTBR_Gustavo",
      team: "CCGTBR",
      birthDate: "30/08/1978",
      email: "",
      instagram: "viarogustavo",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 6,
      countRaces: 35,
      totalPoints: 885,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 885,
      countP1: 17,
      countP2: 10,
      countP3: 4,
      countP4: 0,
      countP5: 1,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 16,
      countVMR: 19,
    },
    {
      idDriver: 5,
      driver: "João Paulo Facci",
      idPsn: "JPFACCI_SPEEDBR",
      team: "SPEEDBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "jpfacci",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 9,
      countRaces: 46,
      totalPoints: 879,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 879,
      countP1: 9,
      countP2: 9,
      countP3: 11,
      countP4: 4,
      countP5: 5,
      countP6: 4,
      countP7: 2,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 4,
      countVMR: 1,
    },
    {
      idDriver: 6,
      driver: "Luis Ferruthio",
      idPsn: "FERRUTH_SPEEDBR",
      team: "SPEEDBR",
      birthDate: "25/01/1968",
      email: "",
      instagram: "luisferruthio",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 9,
      countRaces: 51,
      totalPoints: 820,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 820,
      countP1: 5,
      countP2: 9,
      countP3: 7,
      countP4: 9,
      countP5: 4,
      countP6: 3,
      countP7: 2,
      countP8: 6,
      countP9: 1,
      countP10: 1,
      countP11: 2,
      countP12: 0,
      countP13: 1,
      countP14: 0,
      countPoles: 4,
      countVMR: 4,
    },
    {
      idDriver: 4,
      driver: "Ronald Carvalho",
      idPsn: "roonald_f1",
      team: "BVR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "ronald_benevenuto",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 9,
      countRaces: 47,
      totalPoints: 758,
      countPenals: 2,
      totalPenals: 18,
      validPoints: 740,
      countP1: 7,
      countP2: 9,
      countP3: 8,
      countP4: 4,
      countP5: 6,
      countP6: 4,
      countP7: 2,
      countP8: 2,
      countP9: 2,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 10,
      countVMR: 11,
    },
    {
      idDriver: 3,
      driver: "José Eduardo Filho",
      idPsn: "PCR_Dudu10",
      team: "PCR",
      birthDate: "18/03/1981",
      email: "",
      instagram: "eduardo_ferreira_10",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 5,
      countRaces: 31,
      totalPoints: 550,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 550,
      countP1: 4,
      countP2: 3,
      countP3: 7,
      countP4: 6,
      countP5: 2,
      countP6: 4,
      countP7: 0,
      countP8: 2,
      countP9: 2,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 4,
      countVMR: 4,
    },
    {
      idDriver: 44,
      driver: "Ednaldo Martins",
      idPsn: "KMZ_Naldo",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "ednaldo.geo",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 5,
      countRaces: 28,
      totalPoints: 444,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 444,
      countP1: 1,
      countP2: 0,
      countP3: 5,
      countP4: 5,
      countP5: 4,
      countP6: 8,
      countP7: 3,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 2,
      countVMR: 2,
    },
    {
      idDriver: 36,
      driver: "Fabiano Furini",
      idPsn: "FURINI_SPEEDBR",
      team: "SPEEDBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "fabianofurini",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 5,
      countRaces: 28,
      totalPoints: 442,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 442,
      countP1: 2,
      countP2: 2,
      countP3: 2,
      countP4: 8,
      countP5: 5,
      countP6: 4,
      countP7: 3,
      countP8: 0,
      countP9: 2,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 3,
      countVMR: 2,
    },
    {
      idDriver: 15,
      driver: "Fábian Viegas",
      idPsn: "FABIAN_SPEEDBR",
      team: "SPEEDBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "fabianviegas",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 7,
      countRaces: 33,
      totalPoints: 414,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 414,
      countP1: 0,
      countP2: 1,
      countP3: 4,
      countP4: 5,
      countP5: 5,
      countP6: 4,
      countP7: 4,
      countP8: 3,
      countP9: 3,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 1,
    },
    {
      idDriver: 9,
      driver: "Luis Vilches",
      idPsn: "luisvilches",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "luishvilches",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 6,
      countRaces: 30,
      totalPoints: 309,
      countPenals: 1,
      totalPenals: 3,
      validPoints: 306,
      countP1: 0,
      countP2: 1,
      countP3: 0,
      countP4: 3,
      countP5: 1,
      countP6: 3,
      countP7: 6,
      countP8: 4,
      countP9: 5,
      countP10: 4,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 2,
      driver: "Rafael Garcia",
      idPsn: "rafael_garcia79",
      team: "BVR",
      birthDate: "14/12/1979",
      email: "",
      instagram: "rafa_garciaprod",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 5,
      countRaces: 21,
      totalPoints: 310,
      countPenals: 2,
      totalPenals: 9,
      validPoints: 301,
      countP1: 2,
      countP2: 3,
      countP3: 0,
      countP4: 5,
      countP5: 3,
      countP6: 1,
      countP7: 2,
      countP8: 0,
      countP9: 1,
      countP10: 3,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 3,
      countVMR: 2,
    },
    {
      idDriver: 38,
      driver: "Gerson Garcia",
      idPsn: "Gersão Hamilton",
      team: "MF2",
      birthDate: "09/07/1960",
      email: "",
      instagram: "gersongarcia_51",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 3,
      countRaces: 19,
      totalPoints: 296,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 296,
      countP1: 1,
      countP2: 4,
      countP3: 3,
      countP4: 3,
      countP5: 3,
      countP6: 2,
      countP7: 0,
      countP8: 2,
      countP9: 0,
      countP10: 1,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 3,
      countVMR: 0,
    },
    {
      idDriver: 1,
      driver: "Leonardo Guain",
      idPsn: "leoguain",
      team: "BVR",
      birthDate: "26/07/1988",
      email: "",
      instagram: "leoguain",
      license: "SS",
      image: "/drivers/p_0001.png",
      countChampionships: 3,
      countRaces: 16,
      totalPoints: 278,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 278,
      countP1: 0,
      countP2: 1,
      countP3: 1,
      countP4: 5,
      countP5: 2,
      countP6: 3,
      countP7: 3,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 19,
      driver: "Murilo Silva",
      idPsn: "MYTH_MuriloSilva",
      team: "MYTH",
      birthDate: "01/12/2022",
      email: "",
      instagram: "murilosilva_94",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 8,
      totalPoints: 224,
      countPenals: 1,
      totalPenals: 4,
      validPoints: 220,
      countP1: 4,
      countP2: 1,
      countP3: 0,
      countP4: 1,
      countP5: 0,
      countP6: 1,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 4,
      countVMR: 3,
    },
    {
      idDriver: 10,
      driver: "Marco Aurélio Cerqueira",
      idPsn: "Marco_RJ",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 4,
      countRaces: 23,
      totalPoints: 222,
      countPenals: 1,
      totalPenals: 3,
      validPoints: 219,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 2,
      countP6: 1,
      countP7: 6,
      countP8: 5,
      countP9: 6,
      countP10: 3,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 47,
      driver: "Milton Garcia",
      idPsn: "KMZ-R_SGARCIA",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 5,
      totalPoints: 136,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 136,
      countP1: 2,
      countP2: 2,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 1,
      countP14: 0,
      countPoles: 2,
      countVMR: 3,
    },
    {
      idDriver: 48,
      driver: "Yuri Demetrius",
      idPsn: "kMz_YuriGrusH",
      team: "KMZ",
      birthDate: "24/09/1986",
      email: "",
      instagram: "yuridemetrius",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 11,
      totalPoints: 131,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 131,
      countP1: 0,
      countP2: 1,
      countP3: 0,
      countP4: 0,
      countP5: 2,
      countP6: 0,
      countP7: 3,
      countP8: 4,
      countP9: 0,
      countP10: 1,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 35,
      driver: "Luan Muniz",
      idPsn: "KMZ_Luan_muniz89",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "luanmauriciomuniz",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 9,
      totalPoints: 130,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 130,
      countP1: 0,
      countP2: 2,
      countP3: 1,
      countP4: 1,
      countP5: 1,
      countP6: 4,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 25,
      driver: "Ronan C S Berto",
      idPsn: "Bertorcsb",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "ronancsberto",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 3,
      countRaces: 10,
      totalPoints: 129,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 129,
      countP1: 4,
      countP2: 0,
      countP3: 0,
      countP4: 1,
      countP5: 2,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 1,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 2,
      countVMR: 3,
    },
    {
      idDriver: 45,
      driver: "João Cláudio Pessoa",
      idPsn: "MYTH_JoaoSof",
      team: "MYTH",
      birthDate: "01/12/2022",
      email: "",
      instagram: "_joaosof_",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 4,
      totalPoints: 115,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 115,
      countP1: 3,
      countP2: 1,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 2,
      countVMR: 4,
    },
    {
      idDriver: 7,
      driver: "Marco Santos",
      idPsn: "MarcodiSantti",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "marcodiSantti",
      license: "S",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 9,
      totalPoints: 110,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 110,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 5,
      countP6: 0,
      countP7: 1,
      countP8: 0,
      countP9: 2,
      countP10: 0,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 1,
    },
    {
      idDriver: 8,
      driver: "Jeferson Luis de Souza",
      idPsn: "Jefimwn221",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 10,
      totalPoints: 113,
      countPenals: 1,
      totalPenals: 5,
      validPoints: 108,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 1,
      countP6: 2,
      countP7: 2,
      countP8: 3,
      countP9: 0,
      countP10: 0,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 11,
      driver: "Paulo Henrique Monte",
      idPsn: "PRBR_PH",
      team: "PRBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 11,
      totalPoints: 108,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 108,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 1,
      countP8: 0,
      countP9: 2,
      countP10: 3,
      countP11: 3,
      countP12: 2,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 28,
      driver: "Cléber Carlos Sarmento",
      idPsn: "CLEBER_SPEEDBR",
      team: "SPEEDBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "cleber.carlos.54584",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 4,
      countRaces: 23,
      totalPoints: 104,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 104,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 1,
      countP6: 0,
      countP7: 2,
      countP8: 6,
      countP9: 3,
      countP10: 4,
      countP11: 5,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 16,
      driver: "Marco Godoi",
      idPsn: "Cel_God",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "marco_godoi",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 3,
      countRaces: 14,
      totalPoints: 100,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 100,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 3,
      countP7: 3,
      countP8: 2,
      countP9: 2,
      countP10: 1,
      countP11: 1,
      countP12: 1,
      countP13: 1,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 32,
      driver: "Gustavo Parra",
      idPsn: "Ghustaw",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "gustavo_parra_azevedo",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 10,
      totalPoints: 96,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 96,
      countP1: 0,
      countP2: 1,
      countP3: 1,
      countP4: 0,
      countP5: 1,
      countP6: 2,
      countP7: 2,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 23,
      driver: "Thomas Penteado",
      idPsn: "NeoCactuar",
      team: "BVR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "neokether",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 5,
      totalPoints: 88,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 88,
      countP1: 0,
      countP2: 0,
      countP3: 2,
      countP4: 0,
      countP5: 0,
      countP6: 1,
      countP7: 2,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 30,
      driver: "Alessandro Gratão",
      idPsn: "AleGratao76",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "alessandrogratao",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 10,
      totalPoints: 90,
      countPenals: 1,
      totalPenals: 7,
      validPoints: 83,
      countP1: 0,
      countP2: 1,
      countP3: 2,
      countP4: 0,
      countP5: 1,
      countP6: 1,
      countP7: 1,
      countP8: 0,
      countP9: 2,
      countP10: 0,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 20,
      driver: "Eduardo Schaarschmidt",
      idPsn: "DuduToretto",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "eschaarschmidt",
      license: "SS",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 5,
      totalPoints: 83,
      countPenals: 1,
      totalPenals: 5,
      validPoints: 78,
      countP1: 0,
      countP2: 0,
      countP3: 3,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 13,
      driver: "Eduardo Alecrim",
      idPsn: "alecrim7",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "thegamerboy711",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 7,
      totalPoints: 83,
      countPenals: 1,
      totalPenals: 12,
      validPoints: 71,
      countP1: 1,
      countP2: 1,
      countP3: 1,
      countP4: 0,
      countP5: 1,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 1,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 1,
      countP14: 0,
      countPoles: 2,
      countVMR: 1,
    },
    {
      idDriver: 52,
      driver: "Cláudio Faria",
      idPsn: "CCGTBR-c_faria",
      team: "CCGTBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "claudioantoniofaria",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 12,
      totalPoints: 71,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 71,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 1,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 2,
      countP10: 3,
      countP11: 1,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 50,
      driver: "Cristiano Dutra",
      idPsn: "CCGTBR_Cristiano",
      team: "CCGTBR",
      birthDate: "08/10/1972",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 11,
      totalPoints: 67,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 67,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 3,
      countP9: 0,
      countP10: 2,
      countP11: 2,
      countP12: 3,
      countP13: 1,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 56,
      driver: "Kelvin Carvalho",
      idPsn: "Axelkl19",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 6,
      totalPoints: 65,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 65,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 2,
      countP6: 2,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 1,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 12,
      driver: "Taynam Magalhães",
      idPsn: "TayMaga",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 5,
      totalPoints: 49,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 49,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 2,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 39,
      driver: "Thiago dos S Lima",
      idPsn: "MYTH_THIAGO_AM",
      team: "MYTH",
      birthDate: "01/12/2022",
      email: "",
      instagram: "myth_thiago_am",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 6,
      totalPoints: 48,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 48,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 1,
      countP5: 1,
      countP6: 0,
      countP7: 2,
      countP8: 1,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 1,
    },
    {
      idDriver: 60,
      driver: "José Luiz de O Neto",
      idPsn: "TBR_ZELUIZ87",
      team: "TBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "piloto_zeluiz87",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 43,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 43,
      countP1: 0,
      countP2: 2,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 24,
      driver: "Francisco E da Silva",
      idPsn: "CCGTBR-ELEKTROED",
      team: "CCGTBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 2,
      countRaces: 7,
      totalPoints: 40,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 40,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 1,
      countP8: 0,
      countP9: 2,
      countP10: 1,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 31,
      driver: "Algberg Veloso",
      idPsn: "Berg_pvh",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 4,
      totalPoints: 38,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 38,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 1,
      countP5: 0,
      countP6: 1,
      countP7: 1,
      countP8: 1,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 22,
      driver: "Paulo Tureck",
      idPsn: "TURECK_SPEEDBR",
      team: "SPEEDBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "pauloantoniotureck",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 5,
      totalPoints: 52,
      countPenals: 1,
      totalPenals: 15,
      validPoints: 37,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 2,
      countP8: 1,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 46,
      driver: "Pedro Bernardo",
      idPsn: "Petros_pro",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 4,
      totalPoints: 37,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 37,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 1,
      countP10: 1,
      countP11: 0,
      countP12: 2,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 54,
      driver: "Carlos Celso de Godoy",
      idPsn: "MF2_TattoBrown",
      team: "MF2",
      birthDate: "24/07/1975",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 6,
      totalPoints: 33,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 33,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 3,
      countP10: 0,
      countP11: 1,
      countP12: 1,
      countP13: 1,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 40,
      driver: "Paulo Ramos",
      idPsn: "Paulo_baiano27",
      team: "-",
      birthDate: "27/08/1977",
      email: "",
      instagram: "poll_ba",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 6,
      totalPoints: 38,
      countPenals: 1,
      totalPenals: 6,
      validPoints: 32,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 1,
      countP7: 2,
      countP8: 1,
      countP9: 1,
      countP10: 1,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 18,
      driver: "Juan",
      idPsn: "DJ_CARIOCADZ7",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "cariocadz7",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 3,
      totalPoints: 30,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 30,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 0,
      countP10: 1,
      countP11: 0,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 59,
      driver: "Marcelo Mendes",
      idPsn: "KMZ_MarceloMB",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "kmz_marcelo",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 29,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 29,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 1,
      countP5: 1,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 53,
      driver: "Marco Antonio Soares",
      idPsn: "CRS_BillyBizzuca",
      team: "CRS",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 1,
      totalPoints: 21,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 21,
      countP1: 0,
      countP2: 0,
      countP3: 1,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 34,
      driver: "Leandro Borges",
      idPsn: "Caua-1308",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "lepaborges",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 3,
      countRaces: 5,
      totalPoints: 26,
      countPenals: 1,
      totalPenals: 5,
      validPoints: 21,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 1,
      countP10: 1,
      countP11: 0,
      countP12: 2,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 62,
      driver: "Rodrigo Dionizio",
      idPsn: "KmZRodrigo",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 19,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 19,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 1,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 27,
      driver: "Yuri Stolai",
      idPsn: "Punhalkiller",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "ystolai",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 4,
      totalPoints: 20,
      countPenals: 1,
      totalPenals: 3,
      validPoints: 17,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 1,
      countP7: 0,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 49,
      driver: "Marcos André C da Silva",
      idPsn: "CCGTBR_Borges",
      team: "CCGTBR",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 3,
      totalPoints: 15,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 15,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 55,
      driver: "Thiago Alves da Silva",
      idPsn: "Thiago_Wolf",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 3,
      totalPoints: 15,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 15,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 1,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 61,
      driver: "Rodrigo Furtile",
      idPsn: "Apex_Furtile",
      team: "Apex",
      birthDate: "01/12/2022",
      email: "",
      instagram: "",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 13,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 13,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 1,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 41,
      driver: "Walter R de Moraes",
      idPsn: "waltinhorpm74",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 4,
      totalPoints: 12,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 12,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 1,
      countP10: 1,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 51,
      driver: "Jonathan Diego",
      idPsn: "E-Boss_Jonathan",
      team: "E-Boss",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 12,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 12,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 2,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 58,
      driver: "Ricardo Pavanelli",
      idPsn: "MF2_Pava",
      team: "MF2",
      birthDate: "01/12/2022",
      email: "",
      instagram: "",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 12,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 12,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 1,
      countP8: 0,
      countP9: 0,
      countP10: 1,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 17,
      driver: "Rafael Leite",
      idPsn: "RafaeL1983_SCCP",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "rafaellsousa83",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 9,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 9,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 1,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 37,
      driver: "Lucas Zanivam Macam",
      idPsn: "KMZ_Lucas_ZM",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "lucas_z_m",
      license: "A",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 8,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 8,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 1,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 42,
      driver: "Aldair Martins",
      idPsn: "Aldair_Martins",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "aldairmartins01",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 1,
      totalPoints: 6,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 6,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 1,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 43,
      driver: "Walter G dos Santos",
      idPsn: "Walter-wa42",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 7,
      totalPoints: 4,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 4,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 2,
      countP11: 2,
      countP12: 1,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 26,
      driver: "Luciano Braga",
      idPsn: "KymMastter-kmz",
      team: "KMZ",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 1,
      countRaces: 2,
      totalPoints: 2,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 2,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 1,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 14,
      driver: "Matheus Souza",
      idPsn: "AlR_F0RCE_0NE_01",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 0,
      countRaces: 0,
      totalPoints: 0,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 0,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 57,
      driver: "Luciano Five",
      idPsn: "lppfive",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 0,
      countRaces: 0,
      totalPoints: 0,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 0,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
    {
      idDriver: 29,
      driver: "Bruno Borges",
      idPsn: "Bruno_moby",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 0,
      countRaces: 0,
      totalPoints: 0,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 0,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 1,
      countVMR: 0,
    },
    {
      idDriver: 33,
      driver: "Gustavo Nery",
      idPsn: "Gustavo__Nery",
      team: "-",
      birthDate: "01/12/2022",
      email: "",
      instagram: "-",
      license: "B",
      image: "/drivers/genericDriver.jpg",
      countChampionships: 0,
      countRaces: 0,
      totalPoints: 0,
      countPenals: 0,
      totalPenals: 0,
      validPoints: 0,
      countP1: 0,
      countP2: 0,
      countP3: 0,
      countP4: 0,
      countP5: 0,
      countP6: 0,
      countP7: 0,
      countP8: 0,
      countP9: 0,
      countP10: 0,
      countP11: 0,
      countP12: 0,
      countP13: 0,
      countP14: 0,
      countPoles: 0,
      countVMR: 0,
    },
  ];

  return {
    props: {
      pageTitle,
      description,
      title,
      drivers,
    },
    revalidate: 60 * 60 * 24,
  };
};

export default Pilotos;
